[[_19_FullTextSearch]]
== {FullTextSearch}

=== Description

Ce script est utilisé avant une recherche fulltext pour ajouter ou modifier les filtres de recherche.

=== Paramètres

cf. <<_01_CommonData,attributs communs>>.

[options="noheader",cols="2a,2a,3a"]
|===
|[.sub-header]
_Nom_|[.sub-header]
_Type_|[.sub-header]
_Description_
3+|[.header]
Entrées
|*_searchPhrase*|String|Recherche entrée par l'utilisateur
|*_filter*|IFTFilter|Filtre
|*_contentTypes*|List<String>|Liste des types de contenus sélectionnés pour la recherche

3+|[.header]
Entrées/sorties
|*_result*|*com.digitech.dossier.script.model.impl.result.ScriptResultFullTextSearch*|contient la variable *valid* qui détermine si la recherche est valide,
ainsi que la variable *searchPhrase* qui peut être modifiée
|===

=== Exemples

.Blocage d'une recherche si une certaine condition est rencontrée.
[source,groovy]
----
if (_searchPhrase == "blabla") {
  _result.setValid(false)
  _result.fillKOResult("Ce mot est interdit!")
  return
}
----

.Complétion d'une recherche saisie par l'utilisateur.
[source,groovy]
----
if(_searchPhrase == "digi") {
  _result.setSearchPhrase("digitech")
  _result.fillOKResult("Votre recherche a été modifiée!")
}
----

.Ajout de critères de recherche
[source,groovy]
----
String contentType = "CR"

_filter.addFilterValue(contentType, "CR_RESUME", "test")
_filter.addFilterDate(contentType, "D_MODIF", "01/01/2022", ILocutionModel.Operator.OPERATOR_VALUE_GREATER)
_filter.addFilterValueFromList(contentType, "PRO_APP_OS", "WINDOWS")
_filter.addFilterDates(contentType, "D_CREAT", "01/01/2019", "31/12/2019", ILocutionModel.Operator.OPERATOR_VALUE_BETWEEN)

----


