[[_99_appendixes_groovy]]
=== {groovy} Bonnes pratiques, astuces, ...

[[_99_appendixes_groovy_conventions]]
==== {arcadeged}/{groovy} conventions.

Toutes les variables contextuelles transférées par l'application {arcadeged} (et donc disponibles dans les scripts) sont préfixées du caractère
'[blue-text]#*_*#'.

Le point virgule '[blue-text]#*;*#' en fin d'instruction n'est pas nécessaire.

[[_99_appendixes_groovy_elvis]]
==== Opérateur *elvis*

Le langage {groovy} est (très) proche du langage {java}. En tout cas, le compilateur {groovy} interprète une syntaxe *pure* {java}.

Cependant, le langage se trouve enrichi (_du point de vue de l'auteur de ce document {emoji-ok}_) par certaines caractéristiques, notamment l'opérateur https://docs.groovy-lang.org/next/html/documentation/core-operators.html#_elvis_operator[*elvis*, window="_blank"], un raccourci à l'opérateur ternaire {java}

[source, groovy]
----
displayName = user.name ? user.name : 'Anonymous'
// devient
displayName = user.name ?: 'Anonymous'
----

[[_99_appendixes_groovy_safeop]]
==== Opérateur de navigation _"sécurisé"_

ou dans la langue de _Shakespeare_ *Safe Navigation Operator*.

L'opérateur est identique à _elvis_ et permet d'appel à des méthodes d'objet sans crainte de *NullPointerException*

[source, groovy]
----
// si person ou address ou home est NULL, roadNumber sera NULL
def roadNumber = person?.address?.home?.roadNumber
----

[TIP]
====
Les *2* opérateurs précédemment décrits peuvent être utilisés conjointement !

[source, groovy]
----
def roadNumber = person?.address?.home?.roadNumber ?: 666
----
====

[[_99_appendixes_groovy_scope]]
==== Portée des variables

En {groovy}, pour déclarer une variable

* Soit vous la déclarez directement, *sans préfixe/type*, votre variable - [underline]#Quelle que soit sa position dans le fichier/la classe# - sera alors
*globale* ([underline]#hors méthodes statiques !#)

[source, groovy]
--
monText1 = "je suis une variable globale!"

def localFct() {
  monText2 = "je suis également une variable globale!"
}
--

* Soit vous la préfixez du type souhaité ou du mot clé *def*, celle-ci sera alors *locale* au contexte

[source, groovy]
--
String monText1 = "je suis une variable locale!"

def localFct() {
  def monText2 = "je suis également une variable locale!"
  println(monText1 ?: "inconnue") // print "inconnue"
}
--

[source, groovy]
.exemple complet
----
include::{sourcedir}/scope_variables.groovy[]
----

[[_99_appendixes_groovy_string_interpolation]]
==== Substitution dans les chaines de caractères

Comme indiqué dans la
link:++https://docs.groovy-lang.org/latest/html/documentation/index.html#_string_interpolation++[*documentation*, window="_blank"],
il est possible de formater facilement des messages/chaines de caractères avec des données contextuelles en utilisant le _placeholder_ '[blue-text]#*${}*#' ou '[blue-text]#*$*#'.

[source, groovy]
.String interpolation
----
include::{sourcedir}/string_interpolation.groovy[]
----

<<<