FIELD_CODE_DOC_STATUS=GEN_DOC_STATUS
FIELD_CODE_DOC_VALIDATOR=GEN_DOC_VALIDEUR
FIELD_CODE_DOC_COLLABORATOR=GEN_DOC_COLLAB
FIELD_CODE_DOC_CREAT=GEN_DOC_CREAT
FIELD_CODE_DOC_RANKING=GEN_DOS_PCLASS
FILED_CODE_DOC_ROOT_RANKING=GEN_ROOT_NOM

ITEM_CODE_DOC_STATUS_WAIT_PUB=ATT_PUB
ITEM_CODE_DOC_STATUS_PUB=PUBLIE
ITEM_CODE_DOC_STATUS_CREATED=CREAT
ITEM_CODE_DOC_STATUS_REF_PUB=REFUS_PUB
ITEM_CODE_DOC_STATUS_OUT_OF_DATE=PERIME
ITEM_CODE_DOC_STATUS_DELETED=EFFACE

PROFILE_CODE_VALIDATOR=GEN_VALIDEUR
PROFILE_CODE_COLLABORATOR=GEN_MODIF

COMMENT_PANEL_WIDTH=400
COMMENT_PANEL_HEIGHT=400
