######################
# Configuration Wizard
######################
configuration.login=Admin
configuration.password=Admin

##########
# Workflow
##########
workflow.cacheSize=20000

#################
# Personal Space
#################
personalSpace.clipboardSize=10
personalSpace.historyDocumentSize=10
personalSpace.historySearchSize=10

######
# Misc
######
misc.notificationDaysNumberBeforePasswordExpiration=20
misc.deactivationSortingSearchResultNumber=5000

# Possible values are : BLANK, FIELD_CODE and FIELD_DESCRIPTION
misc.hierarchicalTreeNodeVariableEmptyMode=BLANK