# A DLVA
ORACLE_DRIVER_NAME=oracle.jdbc.driver.OracleDriver
ORACLE_JDBC_CONNECTION_STRING=jdbc:oracle:thin:@10.1.4.95:1521:GEDDOSSIER
ORACLE_USER=dlva_airsuser
ORACLE_PWD=dlva_airsuser
ORACLE_MAX_THREAD=2
ORACLE_SEQ=com.digitech.framework.db.oracle.SequenceOraImpl
URL_DOSSIER=http://srv-ged-47:9292/AirsDossier/
#REQ_HISTORIQUE_COURRIER=select doc_id,docm_svalue from docm_dcou_courrier where doc_id=76239
#select to_char(h.his_date, 'dd-mon-yyyy hh24:mi:ss') as Dt, t.hty_label, h.usr_org_id_from, h.usr_from_fullname, h.usr_fullname, h.his_father_id, h.his_state, h.his_status from courrieruser_prod.historic h, courrieruser_prod.histo_type t where h.hty_id = t.hty_id and h.his_docid=377136 order by h.his_id;
REQ_HISTORIQUE_COURRIER=select to_char(h.his_date, 'dd-mm-yyyy hh24:mi:ss') as DtHr, h.usr_from_fullname as Auteur, t.hty_label as Action, h.usr_fullname as Dest,  h.his_state ||' / '|| h.his_status as State from dlva_courrieruser.historic h, dlva_courrieruser.histo_type t where h.hty_id = t.hty_id and h.his_docid=#ID# and h.his_father_id is null  order by h.his_id desc

#ORACLE_DRIVER_NAME=oracle.jdbc.driver.OracleDriver
#ORACLE_JDBC_CONNECTION_STRING=jdbc:oracle:thin:@10.1.4.68:1521:CLE
#ORACLE_USER=airsuser_DLVA
#ORACLE_PWD=airsuser_DLVA
#ORACLE_MAX_THREAD=2
#ORACLE_SEQ=com.digitech.framework.db.oracle.SequenceOraImpl
#URL_DOSSIER=http://srv-prod-14:9095/AirsDossier/
#REQ_HISTORIQUE_COURRIER=select to_char(h.his_date, 'dd-mm-yyyy hh24:mi:ss') as DtHr, h.usr_from_fullname as Auteur, t.hty_label as Action, h.usr_fullname as Dest,  h.his_state ||' / '|| h.his_status as State from courrieruser_DLVA.historic h, courrieruser_DLVA.histo_type t where h.hty_id = t.hty_id and h.his_docid=#ID# and h.his_father_id is null  order by h.his_id desc
##REQ_HISTORIQUE_COURRIER=select doc_id,docm_svalue from docm_dcou_courrier where doc_id=76239
##select to_char(h.his_date, 'dd-mon-yyyy hh24:mi:ss') as Dt, t.hty_label, h.usr_org_id_from, h.usr_from_fullname, h.usr_fullname, h.his_father_id, h.his_state, h.his_status from courrieruser_prod.historic h, courrieruser_prod.histo_type t where h.hty_id = t.hty_id and h.his_docid=377136 order by h.his_id;



###############
#############  Param  ExportPastelSAE    le format des parametre est ExportPastelSAE.<Le code du CTY sur lequel on fait l'export>.<le code du paramatre>   à reproduire pour chaque CTY qui peut être exporté
###############

# liste des CTY qui peuvent être exporté, séparé par des ,  
# ils doivent tous avoir les champs : ACTES_SEA_ETAT_SAE ACTES_SEA_MSG_SAE ACTES_SEA_ID_PASTELL ACTES_SEA_COTE_ARCHIVE ACTES_SEA_DATE_DEPOT pour générique
#                                et   ACT_ETAT_SAE, ACT_MSG_SAE, ACT_AR_TECHNIQUE, ACT_COTE_ARCHIVE, ACT_DATE_DEPOT     pour DLVA
ExportPastelSAE.LISTE_CTY_OK_FOR_EXPORT=ACTES_DLVA_SEA,ACTES_VILLE_SEA,CP_MARCHE_VILLE,ACTES_VILLE_DEL,CVTHEQUE
ExportPastelSAE.LISTE_CTY_OK_FOR_EXPORT_AUTO=


#### ACTES_DLVA_DEL_SEA  #############################
#champ affiche dans le JSP de Selection et controle
ExportPastelSAE.ACTES_DLVA_SEA.FIELD_FOR_AFF_JSP=ACTES_SEA_LIB
      #séparé par des virgules ,

ExportPastelSAE.ACTES_DLVA_SEA.CTY_CHILD_AUTHORIZED=ACTES_DLVA_DEL,ACTES_DLVA_DEC,ACTES_DLVA_ARR


ExportPastelSAE.ACTES_DLVA_SEA.FIELD_NOT_FOR_EXPORT=ACT_ETAT_SAE,ACT_MSG_SAE,ACT_COTE_ARCHIVE,ACT_AR_TECHNIQUE,ACT_DATE_DEPOT
ExportPastelSAE.ACTES_DLVA_DEL.FIELD_NOT_FOR_EXPORT=ACT_TITRE,ACT_NUMERO_SUIVI
ExportPastelSAE.ACTES_DLVA_DEC.FIELD_NOT_FOR_EXPORT=
ExportPastelSAE.ACTES_DLVA_ARR.FIELD_NOT_FOR_EXPORT=

# répertoire dans le ZIP
ExportPastelSAE.ACTES_DLVA_SEA.REP_PJ_DOC_PRINCIPAL=Documents_annexes
#ExportPastelSAE.ACTES_DLVA_SEA.REP_PJ_DOC_FILS=Délibérations
ExportPastelSAE.ACTES_DLVA_SEA.REP_PJ_DOC_FILS=D\u00e9lib\u00e9rations

#### ACTES_VILLE_DEL_SEA  #################
#champ affiche dans le JSP de Selection et controle
ExportPastelSAE.ACTES_VILLE_SEA.FIELD_FOR_AFF_JSP=ACTES_SEA_LIB

ExportPastelSAE.ACTES_VILLE_SEA.CTY_CHILD_AUTHORIZED=ACTES_VILLE_DEL,ACTES_VILLE_DEC,ACTES_VILLE_ARR
ExportPastelSAE.ACTES_VILLE_SEA.FIELD_NOT_FOR_EXPORT=ACT_ETAT_SAE,ACT_MSG_SAE,ACT_COTE_ARCHIVE,ACT_AR_TECHNIQUE,ACT_DATE_DEPOT
ExportPastelSAE.ACTES_VILLE_DEL.FIELD_NOT_FOR_EXPORT=
ExportPastelSAE.ACTES_VILLE_DEC.FIELD_NOT_FOR_EXPORT=
ExportPastelSAE.ACTES_VILLE_ARR.FIELD_NOT_FOR_EXPORT=


## CP_MARCHE_VILLE
#champ affiche dans le JSP de Selection et controle
ExportPastelSAE.CP_MARCHE_VILLE.FIELD_FOR_AFF_JSP=CP_CODE_MARCHE_V,CP_DATEMAR
ExportPastelSAE.CP_MARCHE_VILLE.CTY_CHILD_AUTHORIZED=


## ACTES_VILLE_DEL    pour exort d'un acte seul
#champ affiche dans le JSP de Selection et controle
ExportPastelSAE.ACTES_VILLE_DEL.FIELD_FOR_AFF_JSP=ACTES_SEA_DATE,ACTES_TYPEDOC,ACT_NUMERO_SUIVI
ExportPastelSAE.ACTES_VILLE_DEL.CTY_CHILD_AUTHORIZED=


## CV_THEQUE AJOUT EAR pour test
#champ affiche dans le JSP de Selection et controle
ExportPastelSAE.CVTHEQUE.FIELD_FOR_AFF_JSP=CV_NOM,CV_PRENOM
ExportPastelSAE.CVTHEQUE.CTY_CHILD_AUTHORIZED=



# nom du repertoire pour l'objet   si vide alors <CTY>-<obj_id>    que pour les CTY FILS pas le père
ExportPastelSAE.ACTES_DLVA_DEL.FIELD_NAME_REP_OBJ_IN_ZIP=

#Generation documents
# Code du champ du type de document :
FIELD_CODE_DOCUMENT_TYPE=MSC_TYPE_DOCUMENT
# Numéro de la valeur à examiner dans la liste d'autorité pour trouver le document à générer
TYPEDOC_POS_VALDEF_MODEL=3

#WKF

