[[_04_temp_folders]]
=== Autres données d'exploitation

Afin d'optimiser ce fonctionnement, notamment dans ces échanges avec la base de données et le serveur {airs},
{arcadegd} met en cache de nombreuses données.

Ces caches peuvent être de type :

. *_mémoire_*: ces données mises en cache permettent d'éviter des appels vers le serveur {airs}. ces caches ont pour propriétés d'être :
** *limités* [underline]#en taille# (nombre d'éléments dans le cache). En cas de dépassement, les éléments les plus anciens sont supprimés du cache
avant ajout
 des nouveaux éléments.
** *initialisés* [underline]#au démarrage# de l'application pour les données de paramétrage.
** *remplis* [underline]#au fil de l'eau# pour les données contextuelles (résultats de recherche, derniers documents consultés, ...)

. *_fichiers_*: ces caches permettent également d'éviter :
** de trop nombreux échanges avec le serveur de stockage de fichiers,
** des conversions incessantes d'un format de fichier vers un autre (ex : *doc* vers *pdf*, *pdf* vers *png*, ...)

L'ensemble des fichiers mis en cache sont inscrits dans le répertoire *<install_tomcat>/webapps/<arcadeged>/tmp*. +
Ce répertoire contient des sous-répertoires dont la description est la suivante :

[cols="2a,4a,4a,2a",options="header"]
|===
|Répertoire|Description|Peut être supprimé ?|Limitation en taille/nombre
|*avatars*|Contient les *avatars* des utilisateurs (auto-générés ou uploadés par les utilisateurs)|[blue]#*Oui*# (automatique, à chaque démarrage)|_aucune_
|*converted*|Contient les documents convertis en *PDF*|[blue]#*Oui*#. Peut être automatiquement vidé à l'arrêt et au démarrage si la clé +
*display.attachment.convertAuto.empty.folder=true* est renseignée dans le fichier *config.properties*|_aucune_
|*documents[/cache]*|Contient les documents téléchargés du filesystem {airs}|[blue]#*Oui*#. Peut être automatiquement vidé à l'arrêt et au démarrage si la clé +
*display.attachment.downloaded.empty.folder=true* est renseignée dans le fichier *config.properties*|*dossier.cache.attachments.max=2048*
|*downloaded*|Répertoire temporaire par session utilisateur|[blue]#*Oui*# (automatique, à chaque démarrage)|_aucune_
|*uploaded*|Répertoire temporaire par session utilisateur, lorsque des documents sont téléversés|[blue]#*Oui*# (automatique, à chaque démarrage)|_aucune_
|*documentViewer[/cache]*|Répertoire stockant les imagettes (_thumbnails_) générées|[blue]#*Oui*#|_10_000_
|===