introduction=introduction.html

connection=identification.html
home=home_portal.html
basket=home_portal.html
history=history_document.html
history_document=home_portal.html
history_search=home_portal.html
clipboard=home_portal.html
recycle_bin=home_portal.html
favorites=favorites.html
personalRequest=personalRequests.html
preference=preferences.html
indexing=home_indexDoc.html
documentAdd=home_createDoc.html
report=reporting.html
userManagement=userMgt.html

search_introduction=search_common.html
search_simple=search_simple.html
search_advanced=search_advanced.html

searchResult_introduction=searchResult_common.html
searchResult_simple=searchResult_simple.html
searchResult_3windows=searchResult_3windows.html

unitView_introduction=unitView_intro.html
unitView_tree=unitView_tree.html
unitView_actions=unitView_actions.html
unitView_attachment_popup=unitView_windowAttachment.html
unitView_tab_attachment=unitView_attachment.html
unitView_tab_comment=unitView_comment.html
unitView_tab_content=unitView_content.html
unitView_tab_history=unitView_history.html
unitView_tab_workflow=unitView_wkf.html

admin_introduction=admin_common.html
admin_documentLocked=admin_docLocked.html
admin_documentState=admin_docState.html
admin_license=admin_licence.html
admin_people=admin_people.html
admin_peoplePerson=admin_peoplePerson.html
admin_peopleCompany=admin_peopleCompany.html
admin_peoplePersonCompanyRelation=admin_peoplePersonCompanyRelation.html
admin_peoplePersonCompanyRelationFunction=admin_peoplePersonCompanyRelationFunction.html
admin_annoRight=admin_annotation_right.html
admin_annoType=admin_annotation_type.html
admin_wizard=admin_wizard.html
