<<<

[[introduction]]
== Introduction

{cmis} (_**C**ontent **M**anagement **I**nteroperability **S**ervices_) est
une norme/un standard géré par le consortium https://www.oasis-open.org/org[*OASIS*^],
dont le but premier est de permettre une interopérabilité entre des systèmes de gestion de contenu (type _geide_ par exemple).

Cette norme permet à des `clients` et des `serveurs` (ou des à des `consommateurs` et des `fournisseurs`)
de _communiquer_, _échanger_, _dialoguer_ ensemble via `*HTTP*` (*REST json*  ou *XML AtomPub*).

La dernière version publiée de la norme est http://docs.oasis-open.org/cmis/CMIS/v1.1/CMIS-v1.1.html[*CMIS 1.1*, window="_blank"].

[NOTE]
====
Les *webservices* de type `SOAP` ne sont pas disponibles car moins performants.
====

{dossier} est compatible avec la norme {cmis} dans sa version *1.1*,
permettant à des applications tierces d'accéder et de gérer le contenu de {dossier}.

Ce document décrit brièvement :

* le format des APIs {cmis} REST (leurs appels)
* une description du format des réponses

