FAC_TYPE_DOC_FIELD_CODE=FAC_TYPE_DOC
AL_FAC_FIELD_CODE=FAC
AL_FAC_DUP_FIELD_CODE=FAC_DUP
AL_FAC_CONTRAT_FIELD_CODE=CONTRAT
AL_AVOIR_FIELD_CODE=AVO

ENG_NUM_CODE =ENG_NUM
ENG_VERROU_CODE =ENG_VERROU
D_DOC_ENG_CODE =D_DOC_ENG
YES_CODE =OUI
NO_CODE =NON

CONNECT_BDD_REF_ENG_LOGIN=LAPROVENCE_AIRSFACT
CONNECT_BDD_REF_ENG_MDP=LAPROVENCE_AIRSFACT
CONNECT_BDD_REF_ENG_SERVEUR=jdbc:oracle:thin:@srv-prod-06:1521:PFA
 
CONNECT_BDD_CIPRES_LOGIN=LAPROVENCE_AIRSFACT
CONNECT_BDD_CIPRES_MDP=LAPROVENCE_AIRSFACT
CONNECT_BDD_CIPRES_SERVEUR=jdbc:oracle:thin:@srv-prod-06:1521:PFA

CONNECT_BDD_AIRS_CAPTURE_LOGIN=root
CONNECT_BDD_AIRS_CAPTURE_MDP=digimysql
CONNECT_BDD_AIRS_CAPTURE_SERVEUR=jdbc:mysql://srv-prod-13:3306/airsfact

CONNECT_BDD_AIRS_DOSSIER_LOGIN=root
CONNECT_BDD_AIRS_DOSSIER_MDP=digimysql
CONNECT_BDD_AIRS_DOSSIER_SERVEUR=jdbc:mysql://srv-prod-13:3306/airsuser
                                    
POOL_NAME=bddFact
POOL_NAME_CAPTURE=bddCapture
POOL_NAME_DOSSIER=bddDossier
POOL_NAME_ENGAG=bddEng
POOL_NAME_CIPRES=bddCipres

FAC_TTC_FIELD_CODE =FAC_TTC
FAC_HT_FIELD_CODE =FAC_HT
FAC_TVA_TOTAL_FIELD_CODE =FAC_TVA_TOTAL
ENG_NUM_FIELD_CODE =ENG_NUM
FAC_MAT_FOUR_CODE =FOUR_MAT
FAC_EMETTEUR_FIELD_CODE=EMETTEUR
FAC_SOC_FIELD_CODE=SOC
FAC_DATE_FIELD_CODE=FAC_DATE
FAC_DATE_ECH_FIELD_CODE=FAC_DATE_ECHEA
FAC_DATE_VALID_FIELD_CODE=FAC_DATE_VALID
FAC_ENG_VERROU_FIELD_CODE=ENG_VERROU
FAC_ETAT_FIELD_CODE=FAC_ETAT
FAC_MONTANT_HT_FIELD_CODE=FAC_HT
FAC_ASSISTANT_CODE=FAC_TRAIT1
FAC_ENG_CT_CODE=D_DOC_ENG
FAC_VERROU_OUI_CODE =OUI
FAC_VALID1_CODE=FAC_VALID1
FAC_VALID12_CODE=FAC_VALID12
FAC_VALID2_CODE=FAC_VALID2

FAC_NOM_TACHE_BLOQUE=Bloquee1
FAC_NOM_TACHE_AVALIDER1=AValider1
FAC_NOM_TACHE_AVALIDER2=AValider2
FAC_NOM_TACHE_RESTEAPAYER=ResteAPayer
FAC_NOM_TACHE_ATRAITER=ATraiter
FAC_NOM_TACHE_AENGAGER=AEngager
FAC_NOM_TACHE_AENGAGERPOUSSER=AEngagerPousser
    
FAC_NOM_SORTIE_BAP=BonAPayer
FAC_NOM_SORTIE_BAPPARTIEL=BonAPayerPartiel
FAC_NOM_SORTIE_BLOQUER=Bloquer
FAC_NOM_SORTIE_AVALIDER=AValider
FAC_NOM_SORTIE_AENGAGER=AEngager
FAC_NOM_SORTIE_STANDBY=Standby

FAC_PARAMETRE_ACTEUR=acteur
FAC_ATTRIBUT_ASSISTANT_CODE=UtilTrait
FAC_ATTRIBUT_VALID1_CODE=UtilValid1
FAC_ATTRIBUT_VALID12_CODE=UtilValid12

FAC_ETAT_AVALIDER =113
FAC_ETAT_BAP =115
FAC_ETAT_BAPPARTIEL =116

USR_OPT_MONTANT_MAX =MONTANT_MAX_VALIDATION
