[[appendix_dossiercontext]]
=== DossierContext modèles

==== *getContentTypeLinks*
La réponse est retournée sous forme de chaîne de caractères,
au format {xml} ({soap}) ou {json} ({rest})

Celle-ci contient les informations suivantes :

Liste de flux
[cols="2a,3a,3a,1a",options="header"]
.Paramètres en sortie
|===
|Paramètre|Description|Observations|Type
|*code*|Code du flux||_string_
|*label*|Nom du flux||_string_
|===


[[appendix_dossiercontext_WSContentTypeInfosType]]
==== *WSContentTypeInfosType* ({rest})

[cols="2a,3a,3a,1a",options="header"]
.Paramètres en sortie
|===
|Paramètre|Description|Observations|Type
|*code*|Code du type de contenu||_string_
|*id*|Identifiant AIRS du type de contenu||_integer_
|*description*|Nom du type de contenu||_string_
|*readSecretLevels*|Liste des niveaux de secret associés à ce type de contenu (_consultation_)|{rest} seulement|liste d'_integer_
|*writeSecretLevels*|Liste des niveaux de secret associés à ce type de contenu (_création/mise à jour_)|{rest} seulement|liste d'_integer_
4+^|*linksInfosList > childContentType*
|*code*|Code du type de contenu fils||_string_
|*id*|Identifiant AIRS du type de contenu fils||_integer_
|*description*|Nom du type de contenu fils||_string_
|*linksInfosList*|Informations du type de contenu fils| Contient une liste vide si le type de contenu fils n'a pas d'enfant|structure _linksInfosList_
4+^|*linksInfosList > linkedFieldInfos*
|*fieldChildcode*|Code du champ utilisé par le type de contenu fils pour la liaison père-fils||_string_
|*fieldFathercode*|Code du champ utilisé par le type de contenu père pour la liaison père-fils||_string_
|===

[[appendix_dossiercontext_WSContentTypeInfo]]
==== *WSContentTypeInfo* ({rest})

[cols="2a,3a,3a,1a",options="header"]
.Paramètres en sortie
|===
|Paramètre|Description|Observations|Type
|*code*|Code du type de contenu||_string_
|*label*|Libellé du type de contenu||_string_
|*mode*|Correspond au *mode* (type de fiche) demandé pour la liste des champs|Répétition du paramètre en entrée|_string_
|*readSecretLevels*|Liste des niveaux de secret associés à ce type de contenu (_consultation_)||liste d'_integer_
|*writeSecretLevels*|Liste des niveaux de secret associés à ce type de contenu (_création/mise à jour_)||liste d'_integer_
|*children*|Codes des types de contenus enfant de celui-ci||_string_
4+^|*fields*, liste des champs disponibles
|*id*|Identifiant ({airs}) du champ||_integer_
|*code*|Code du champ||_string_
|*label*|Libellé du champ||_string_
|*type* 2+^|Type de champ|_string_
|_Valeurs possibles :_ 3+|

* *id*: champ _identifiant_ {airs}
* *secretLevel*: champ de type _niveau de secret_
* *text*: champ de type _string/texte_
* *date*: champ de type _date_
* *float*: champ de type _float_
* *numeric*: champ de type _numeric_
* *auto-increment*: champ de type _auto-increment_
* *reference*: champ de type _référence_, pouvant être de sous-catégorie :
** *user*: champ associé à un _utilisateur_
** *organization*: champ associé à un _organisation_
** *authority*: champ associé à une _liste d'autorité_

|*required*|Champ requis ?|attribut *absent* si *mode==CONFIG*|_boolean_
|*readonly*|Champ en lecture seule ?|attribut *absent* si *mode==CONFIG*|_boolean_
|*multivalued*|Champ multi-valué ?||_boolean_
|*reference*|Champ référence ?|si _true_, cela signifie que ce champ est rattaché à une liste (utilisateur, organisation, liste d'autorité)|_boolean_
|*system*|Champ _système_ ?|Si _true_, champ interne, géré par le serveur {airs}|_boolean_
|*choices*|Liste des valeurs possibles pour les champs de type _référence_|sous la forme *libellé*/*valeur*|_map_
|===

[[dossiercontext_getcontenttypejson_new_response2]]
==== WSContentTypeInfo, *mode==CONFIG*

[source,json]
----
{
  "contentType": {
    "code": "CR",
    "label": "Compte rendu",
    "mode": "CONFIG",
    "readSecretLevels": [
      10
    ],
    "writeSecretLevels": [
      10
    ],
    "children": [],
    "fields": [
      {
        "id": 1,
        "code": "D_CREAT",
        "label": "Date de création",
        "type": "date",
        "reference": false,
        "multivalued": false,
        "system": true
      },
      {
        "id": 2,
        "code": "D_MODIF",
        "label": "Date de modification",
        "type": "date",
        "reference": false,
        "multivalued": false,
        "system": true
      },
      {
        "id": 123,
        "code": "CR_DES",
        "label": "Désignation",
        "type": "text",
        "reference": false,
        "multivalued": false,
        "system": false
      },
      {
        "id": 124,
        "code": "CR_DATE",
        "label": "Date événement",
        "type": "date",
        "reference": false,
        "multivalued": false,
        "system": false
      },
      {
        "id": 125,
        "code": "CR_RESUME",
        "label": "Résumé",
        "type": "text",
        "reference": false,
        "multivalued": false,
        "system": false
      },
      {
        "id": 126,
        "code": "CR_THEME",
        "label": "Thématique",
        "type": "authority",
        "reference": true,
        "multivalued": false,
        "system": false
      },
      {
        "id": 127,
        "code": "CR_REDACTEUR",
        "label": "Rédacteur",
        "type": "user",
        "reference": true,
        "multivalued": false,
        "system": false
      },
      {
        "id": 172,
        "code": "CORRES",
        "label": "correspondent",
        "type": "text",
        "reference": false,
        "multivalued": false,
        "system": false
      },
      {
        "id": 173,
        "code": "MULTI",
        "label": "test champs multi",
        "type": "text",
        "reference": false,
        "multivalued": true,
        "system": false
      },
      {
        "id": 174,
        "code": "MASQUE_NUM",
        "label": "test masque",
        "type": "numeric",
        "reference": false,
        "multivalued": false,
        "system": false
      },
      {
        "id": 175,
        "code": "T_PRIOR",
        "label": "Priorité",
        "type": "authority",
        "reference": true,
        "multivalued": false,
        "system": false
      }
    ]
  }
}
----

[[dossiercontext_getcontenttypejson_new_response3]]
==== WSContentTypeInfo, *mode==CONFIG*, choices==true

[source,json]
----
{
  "contentType": {
    "code": "CR",
    "label": "Compte rendu",
    "mode": "CONFIG",
    "readSecretLevels": [
      10
    ],
    "writeSecretLevels": [
      10
    ],
    "children": [],
    "fields": [
      {
        "id": 1,
        "code": "D_CREAT",
        "label": "D_CREAT",
        "type": "date",
        "reference": false,
        "multivalued": false,
        "system": true
      },
      {
        "id": 2,
        "code": "D_MODIF",
        "label": "D_MODIF",
        "type": "date",
        "reference": false,
        "multivalued": false,
        "system": true
      },
      {
        "id": 123,
        "code": "CR_DES",
        "label": "CR_DES",
        "type": "text",
        "reference": false,
        "multivalued": false,
        "system": false
      },
      {
        "id": 124,
        "code": "CR_DATE",
        "label": "CR_DATE",
        "type": "date",
        "reference": false,
        "multivalued": false,
        "system": false
      },
      {
        "id": 125,
        "code": "CR_RESUME",
        "label": "CR_RESUME",
        "type": "text",
        "reference": false,
        "multivalued": false,
        "system": false
      },
      {
        "id": 126,
        "code": "CR_THEME",
        "label": "CR_THEME",
        "type": "authority",
        "reference": true,
        "multivalued": false,
        "system": false,
        "choices": {
          "Réunion Transverse": 172,
          "Groupe de Travail": 173,
          "Entreprise Libérée": 174,
          "Réunion Générale": 175,
          "Comité Stratégique": 176,
          "Comité Directeur": 177,
          "Roadmap": 180
        }
      },
      {
        "id": 127,
        "code": "CR_REDACTEUR",
        "label": "CR_REDACTEUR",
        "type": "user",
        "reference": true,
        "multivalued": false,
        "system": false,
        "choices": {
          "A.PIRIM": 33,
          "Achat Patrick": 79,
          "Adm Adm": 1,
          "Adm Dossier": 3,
          "Admin Administrateur": 108,
          "Aquilina Stephane": 73,
          "Aramburu Eric": 8,
          "Arnaud Yannick": 102,
          "Balladon Dorian": 328,
          "Belkelai Laurent": 91,
          "Bensidhoum Farida": 80,
          "Bihan-poudec Theo": 106,
          "Billon Benjamin": 17,
          "Bonnans Claire": 82,
          "Boussage Aurélien": 19,
          "Brossas Nicolas": 12,
          "Cabrit Christine": 25,
          "Cabrit Sebastien": 40,
          "Carole Olivier": 42,
          "Charpentier Celine": 100,
          "Chenh Simon": 20,
          "Chesneau Serge": 57,
          "Clémenson Gabriel": 31,
          "Cogneau Daniel": 81,
          "Colonna D'istria Franck": 30,
          "Couderc Joel": 86,
          "D'isanto Mathias": 15,
          "Debouillanne Julien": 54,
          "Delaye Olivier": 47,
          "Doladille Denis": 14,
          "Felix Nicolas": 97,
          "Froche Christophe": 103,
          "Gadaut Frederic": 95,
          "Gauthier Bruno": 21,
          "Ghelardi Alexis": 90,
          "Grinan Nicolas": 88,
          "Guentas Fatima": 58,
          "Guiraud Laurent": 51,
          "Haddad Nazim": 41,
          "Jaubert Didier": 23,
          "Jossinet Pierrick": 59,
          "Kanjou Olivier": 104,
          "Khalid Ahlem": 36,
          "Kolinsky Nicolas": 64,
          "Lambot Emmanuel": 16,
          "Lamore Angela": 45,
          "Lebrun Christophe": 5,
          "Ln_g0s8g)7xhod!vq9i/$d' Fn_g0s8g)7xhod!vq9i/$d'": 327,
          "Ln_lv[dg Fn_lv[dg": 334,
          "Madjid Dahbia": 26,
          "Mannini Marie-jose": 37,
          "Marine Michael": 28,
          "Merzereau Lucile": 38,
          "Mijoint Olivier": 39,
          "MJ.CADON": 65,
          "Moulay Mohamed": 84,
          "Muscarnera Julien": 11,
          "Muscarnera Sylvain": 98,
          "Neffaa Salah": 107,
          "Olivier Lucas": 10,
          "Panchot Magali": 34,
          "Param Dossier": 2,
          "Poli Marie-pierre": 32,
          "Priez Théo": 48,
          "Rakotomavo Mirana": 350,
          "Rey Pierre-henri": 27,
          "Robert Jean-jacques": 85,
          "Roth Philippe": 101,
          "Roth Sarah": 87,
          "Ruscony Nadege": 78,
          "Scarpulla Christelle": 18,
          "Sittler Christelle": 94,
          "Utilisateur Dossier": 4,
          "Viet Bastien": 29,
          "Vignoli Fabrice": 46,
          "Zannone Damien": 6
        }
      },
      {
        "id": 172,
        "code": "CORRES",
        "label": "CORRES",
        "type": "text",
        "reference": false,
        "multivalued": false,
        "system": false
      },
      {
        "id": 173,
        "code": "MULTI",
        "label": "MULTI",
        "type": "text",
        "reference": false,
        "multivalued": true,
        "system": false
      },
      {
        "id": 174,
        "code": "MASQUE_NUM",
        "label": "MASQUE_NUM",
        "type": "numeric",
        "reference": false,
        "multivalued": false,
        "system": false
      },
      {
        "id": 175,
        "code": "T_PRIOR",
        "label": "T_PRIOR",
        "type": "authority",
        "reference": true,
        "multivalued": false,
        "system": false,
        "choices": {
          "Document urgent": 243,
          "Normal": 244
        }
      }
    ]
  }
}
----

[[appendix_dossiercontext_WSContentTypeLinkInfo]]
==== *WSContentTypeLinkInfo* ({rest})

[cols="2a,3a,3a,1a",options="header"]
.Paramètres en sortie
|===
|Paramètre|Description|Observations|Type
|*code*|Code du type de contenu||_string_
|*label*|Libellé du type de contenu||_string_
4+^|*children*, liste des content-types _enfants_, de type *WSContentTypeLinkInfo*
4+^|*linkedFields*, information sur les champs servant de liens entre content-types.
|*code*|Code du type de contenu *cible*||_string_
|*parentFieldCode*|Code du type de contenu *source* (_parent_)||_string_
|===

