spnego.allow.basic=true
spnego.allow.localhost=true
spnego.allow.unsecure.basic=true
spnego.allow.delegation=false
spnego.login.client.module=spnego-client
## ce fichier doit etre placé dans le repertoire xml de la webapp
spnego.krb5.conf=krb5.conf 
## ce fichier doit etre placé dans le repertoire xml de la webapp
spnego.login.conf=login.conf
spnego.preauth.username=krb5airs
spnego.preauth.password=123soleil
spnego.login.server.module=spnego-server
spnego.prompt.ntlm=true
spnego.logger.level=1