################################################################################
#									WSDocumentOAI							   #		
################################################################################
# Configuration générale                    #
#############################################
# Code du Type de contenu
doc.content.type=DOCUMENT_ASSURE
# Code du champ NSS
doc.nss.field=N_NSS
# Code du champ Numéro de demande
doc.ndem.field=N_DEM
# Code du champ Groupe de document
doc.groupetype.field=AL_ASSURE_GROUPE_DOC
# Code du champ Type de document
doc.doctype.field=AL_ASSURE_TYPE_DOC
# ID du champ Type de document
doc.groupetype.field.id=10
# Code du champ Orga (Définition sur le flux d'entrée)
doc.orga.field=ORGA
# Code du champ Date du document
doc.date.field=D_VALEUR
# Code du champ ID Gedos permettant de savoir si le document est un document de reprise GEDOS
doc.idgedos.field=IDGEDOS
# Code du champ Création du document
doc.user.create.field=U_CREAT
# Code du champ Gestionnaire actif
doc.gest.field=U_GEST
# Code du champ Nombre de pages
doc.numpages.field=NOMBRE_PAGES
# Code du champ Nom - Prénom
doc.name.field=NOM
# Code du champ Gestionnaire (Pas utilisé en GED, uniquement pour information dans Doc.Series)
doc.gestionnaires_info.field=GESTIONNAIRES
# Code du champ Gestionnaires (Utilisé pour le Workflow)
wf.gest.field=U_GESTS
# Code du champ du statut du Workflow
wf.status.field=AL_WKF_STATUT
# ID du statut Workflow "Pour transfert ou prise en compte"
wf.status.active=7
# ID du statut Workflow "Gestionnaire inconnu"
wf.status.unknown=10
# ID du statut Workflow "Archivé"
wf.status.archive=11
# Code du champ Workflow (Pas utilisé en GED, uniquement pour donner l'information au WebService)
wf.active.field=WF
# Valeur attendu pour le code wf.active.field si un flux Workflow doit être initié
wf.active.value=OUI
# Code du champ Numéro de courrier
ocr.cour.field=N_COUR
# Code du champ permettant de savoir si un document avec le numéro courrier a déjà été traité
ocr.flag.field=FLAG_OCR
# Code du champ Nom (Pas utilisé en GED, uniquement pour information dans Doc.Series)
identity.field=NAME
# Code du champ Langage (Pas utilisé en GED, uniquement pour information dans Doc.Series)
language.field=LANGUAGE

#############################################
# Options				                    #
#############################################
# Le WebService doit-il calculé le nombre de page du document (0=NON; 1=OUI)
count.page.active=1
# Définition du niveau confidentiel 600 par WebAI (0=NON; 1=OUI)
webai.confidentiel.active=1
# Définition du Nom-Prénom par WebAI (0=NON; 1=OUI)
doc.name.active=1
# Définition du niveau de secret LFA par le numéro de demande (0=NON; 1=OUI)
doc.ndem.active=1
# Si doc.ndem.active est actif alors définition de numéro de demande pour traitement
doc.ndem.3333=700
doc.ndem.9876=550
#doc.confid.folders=3333
# Si doc.ndem.active est actif alors niveau de secret défini pour les LFA
#doc.ndem.secretlevel=700
# Si doc.doctype.active est actif alors définition de le type de document pour traitement - doc.ndem.active est prioritaire (0=NON; 1=OUI)
doc.doctype.active=0
# Si doc.doctype.active est actif alors niveau de secret défini pour les LFA
doc.doctype.secretlevel=
# Définition du niveau de secret pour les documents confidentiel
doc.webai_confidentiel.secretlevel=600
# Nom de l'utilisateur Confidentiel permettant de définir Confidentiel comme gestionnaire du document afin de mettre ce document dans la corbeille Confidentiel
doc.webai_gestionnaire_login=CONFIDENTIEL
# Le WebService doit-il donné les droits en écriture sur un document envoyé par un utilisation ayant un profil lecture seul
doc.edit_for_read_profil.active=1
# Flux Workflow - Définition si un workflow d'un document confidentiel va dans la corbeille confidentiel. 
# Si non alors il va dans la corbeille du gestionnaire actif directement (0=NON; 1=OUI)
confidentiel.distribution.basket.active=1
# Flux Workflow - Si la règle de gestion retourne aucun utilisateur alors le document est archivé sinon corbeille TEMP (0=NON; 1=OUI)
ocr.archive_if_no_gest.active=0
# Vérifier dans WebAI si le numéro OCR est en attente (via requete webai.db.check)
ocr.check.active=0
# Pour la définition du Workflow OCR 
webai.db.ocr.use_ocr.active=0
ocr.return.file.path=/data/int1/journaling/ocrReturns/processing

# Configuration Web@AI DB
webai.db.class=com.ibm.db2.jcc.DB2Driver
webai.db.url=jdbc:db2://ai0wairs4.gilai.oai.ch:50000/INTWAIRS
webai.db.user=vsrdo
	# password crypté
webai.db.password=dnNyZG80R2lsYWk=

webai.db.gest=SELECT aivsweb.AIDPATT.DATTUT AS GEST FROM aivsweb.AIDPATT INNER JOIN aivsweb.AIDPDEM ON (aivsweb.AIDPDEM.DDEMID = aivsweb.AIDPATT.DDEMID) INNER JOIN aivsweb.AIDPGDE ON (aivsweb.AIDPGDE.DGDEID = aivsweb.AIDPDEM.DGDEID) INNER JOIN aivsweb.AISPDOS ON (aivsweb.AISPDOS.SDOSID = aivsweb.AIDPGDE.SDOSID) INNER JOIN aivsweb.TITIERP ON (aivsweb.TITIERP.HTITIE = aivsweb.AISPDOS.SDOSAS) INNER JOIN aivsweb.TIPERSP ON (aivsweb.TIPERSP.HTITIE = aivsweb.TITIERP.HTITIE) INNER JOIN aivsweb.TIPAVSP ON (aivsweb.TIPAVSP.HTITIE = aivsweb.TITIERP.HTITIE) WHERE aivsweb.TITIERP.HTPPHY = '1' AND aivsweb.TIPAVSP.HXNAVS like '#VALUE_TO_REPLACE#%' AND aivsweb.AIDPATT.DATTAC=22002024 AND aivsweb.AIDPATT.DATTTY=22000054 ORDER BY aivsweb.AIDPATT.DATTDE DESC, aivsweb.AIDPATT.DATTID DESC fetch first 1 row only
webai.db.confidential=SELECT 'VSCONF' FROM aivsweb.AISPDOS INNER JOIN aivsweb.TITIERP ON (aivsweb.TITIERP.HTITIE = aivsweb.AISPDOS.SDOSAS) INNER JOIN aivsweb.TIPERSP ON (aivsweb.TIPERSP.HTITIE = aivsweb.TITIERP.HTITIE) INNER JOIN aivsweb.TIPAVSP ON (aivsweb.TIPAVSP.HTITIE = aivsweb.TITIERP.HTITIE) WHERE aivsweb.TITIERP.HTPPHY='1' AND aivsweb.TIPAVSP.HXNAVS like '#VALUE_TO_REPLACE#%' AND aivsweb.AISPDOS.SDOSCF = '1'
webai.db.confidential_all=SELECT aivsweb.TIPAVSP.HXNAVS FROM aivsweb.AISPDOS INNER JOIN aivsweb.TITIERP ON (aivsweb.TITIERP.HTITIE = aivsweb.AISPDOS.SDOSAS) INNER JOIN aivsweb.TIPERSP ON (aivsweb.TIPERSP.HTITIE = aivsweb.TITIERP.HTITIE) INNER JOIN aivsweb.TIPAVSP ON (aivsweb.TIPAVSP.HTITIE = aivsweb.TITIERP.HTITIE) WHERE aivsweb.TITIERP.HTPPHY='1' AND aivsweb.AISPDOS.SDOSCF = '1'
webai.db.req1=SELECT aivsweb.AIDPATT.DATTUT AS GEST FROM aivsweb.AIDPATT INNER JOIN aivsweb.AIDPDEM ON (aivsweb.AIDPDEM.DDEMID = aivsweb.AIDPATT.DDEMID) INNER JOIN aivsweb.AIDPGDE ON (aivsweb.AIDPGDE.DGDEID = aivsweb.AIDPDEM.DGDEID) INNER JOIN aivsweb.AISPDOS ON (aivsweb.AISPDOS.SDOSID = aivsweb.AIDPGDE.SDOSID) INNER JOIN aivsweb.TITIERP ON (aivsweb.TITIERP.HTITIE = aivsweb.AISPDOS.SDOSAS) INNER JOIN aivsweb.TIPERSP ON (aivsweb.TIPERSP.HTITIE = aivsweb.TITIERP.HTITIE) INNER JOIN aivsweb.TIPAVSP ON (aivsweb.TIPAVSP.HTITIE = aivsweb.TITIERP.HTITIE) WHERE aivsweb.TITIERP.HTPPHY = '1' AND aivsweb.TIPAVSP.HXNAVS like '#VALUE_TO_REPLACE#%' AND NOT EXISTS (SELECT PLIEC1 FROM aivsweb.AIPPLIE where PLIETY = 22002042 AND PLIEC1 = aivsweb.AIDPATT.DATTID) AND NOT EXISTS (SELECT PLIEC1 FROM aivsweb.AIPPLIE where PLIETY = 22002044 AND PLIEC1 = aivsweb.AIDPATT.DATTID) AND aivsweb.AIDPATT.DATTAC = 22002024 AND aivsweb.AIDPATT.DATTTY = 22002117 ORDER BY aivsweb.AIDPATT.DATTDE DESC, aivsweb.AIDPATT.DATTID DESC fetch first 1 row only
webai.db.req2=SELECT aivsweb.AIDPATT.DATTUT AS GEST FROM aivsweb.AIDPATT INNER JOIN aivsweb.AIDPDEM ON (aivsweb.AIDPDEM.DDEMID = aivsweb.AIDPATT.DDEMID) INNER JOIN aivsweb.AIDPGDE ON (aivsweb.AIDPGDE.DGDEID = aivsweb.AIDPDEM.DGDEID) INNER JOIN aivsweb.AISPDOS ON (aivsweb.AISPDOS.SDOSID = aivsweb.AIDPGDE.SDOSID) INNER JOIN aivsweb.TITIERP ON (aivsweb.TITIERP.HTITIE = aivsweb.AISPDOS.SDOSAS) INNER JOIN aivsweb.TIPERSP ON (aivsweb.TIPERSP.HTITIE = aivsweb.TITIERP.HTITIE) INNER JOIN aivsweb.TIPAVSP ON (aivsweb.TIPAVSP.HTITIE = aivsweb.TITIERP.HTITIE) WHERE aivsweb.TITIERP.HTPPHY = '1' AND aivsweb.TIPAVSP.HXNAVS like '#VALUE_TO_REPLACE#%' AND aivsweb.AIDPATT.DATTAC=22002024 AND aivsweb.AIDPATT.DATTTY=22000054 ORDER BY aivsweb.AIDPATT.DATTDE DESC, aivsweb.AIDPATT.DATTID DESC fetch first 1 row only
webai.db.req3=SELECT (CASE WHEN aivsweb.TITIERP.HTTLAN = 503001 THEN 'TEMP_FR' WHEN aivsweb.TITIERP.HTTLAN = 503002 THEN 'TEMP_DE' ELSE '' END) as GEST FROM aivsweb.AISPDOS INNER JOIN aivsweb.TITIERP ON (aivsweb.TITIERP.HTITIE = aivsweb.AISPDOS.SDOSAS) INNER JOIN aivsweb.TIPERSP ON (aivsweb.TIPERSP.HTITIE=aivsweb.TITIERP.HTITIE) INNER JOIN aivsweb.TIPAVSP ON (aivsweb.TIPAVSP.HTITIE=aivsweb.TITIERP.HTITIE) WHERE aivsweb.TITIERP.HTPPHY='1' AND aivsweb.TIPAVSP.HXNAVS like '#VALUE_TO_REPLACE#%'
webai.db.req4=
webai.db.req5=
webai.db.req6=
webai.db.check=SELECT avs.hxnavs FROM aivsweb.jojpjou jou LEFT JOIN aivsweb.jojpgjo gjo ON gjo.jgjoid = jou.jgjoid INNER JOIN aivsweb.jojprep rep ON rep.jjouid = jou.jjouid AND rep.jrepty = '22002006' INNER JOIN aivsweb.jojpred red ON rep.jjouid = red.jjouid INNER JOIN aivsweb.enepenv env ON env.eenvid = red.jredir INNER JOIN aivsweb.eneppge pge ON env.eenvid = pge.eenvid INNER JOIN aivsweb.enepvpg vpg ON vpg.epgeid = pge.epgeid INNER JOIN aivsweb.aispdos dos ON dos.sdosid = Int(rep.jrepip) INNER JOIN aivsweb.titierp tie ON tie.htitie = dos.sdosas INNER JOIN aivsweb.tipavsp avs ON avs.htitie = tie.htitie WHERE  pge.epgens = 'GEDOCR' AND vpg.evpgva = '##num_ocr##'
webai.db.field=GEST
replace.value=#VALUE_TO_REPLACE#

#
# Web@AI 3 - Configuration
################################################################################
##URL's
webai.url.token=https://int1-webai3.gilai.oai.ch/authentification-service/auth
webai.url.gestionnaire=https://int1-webai3.gilai.oai.ch/webai/api/postman/gestionnaire
webai.url.name.nss.by.ocr=https://int1-webai3.gilai.oai.ch/webai/api/assure/informations
webai.url.name.by.nss=https://int1-webai3.gilai.oai.ch/webai/api/assure/informations
webai.url.gestionnaire.actif=https://int1-webai3.gilai.oai.ch/webai/api/postman/gestionnaireactif
webai.url.isconfidentiel=https://int1-webai3.gilai.oai.ch/webai/api/assure/confidentiel
webai.url.intervenants=https://int1-webai3.gilai.oai.ch/webai/api/assure/intervenants

##Requetes JSON
webai.json.request.token={"login":"GIAIRS","password":"D1g1tech"}
webai.json.request.nss.gestionnaire={"nss":"##NSS##","ocr":""}
webai.json.request.ocr.gestionnaire={"nss":"","ocr":"##OCR##"}
webai.json.request.name.nss.by.ocr={"ocr":"##OCR##"}
webai.json.request.name.by.nss={"nss":"##NSS##"}
webai.json.request.gestionnaire.actif.by.nss={"nss":"##NSS##"}
webai.json.request.isconfidentiel.by.nss={"nss":"##NSS##"}
webai.json.request.intervenants={"nss":"##NSS##"}

##Information à récupérer
webai.json.request.gestionnaire.nss.information=utilisateur
webai.json.request.name.by.ocr.information=nom
webai.json.request.nss.by.ocr.information=nss
webai.json.request.name.by.nss.information=nom
webai.json.request.gestionnaire.actif.information=utilisateur
webai.json.request.isconfidentiel.information=confidentiel
webai.json.request.intervenant.information=intervenants
webai.json.request.intervenant.information.nom=nom
webai.json.request.intervenant.information.email=email

##Séparateur informations reçues
separateur.webai=;

#############################################
# Messages				                    #
#############################################
message.error.nss.fr=Envoi impossible car NSS invalide
message.error.nss.de=Vers.–Nr. nicht korrekt, Übermittlung nicht möglich
message.error.nss.it=Il numero NSS non è corretto
message.error.login.fr=Identifiants incorrects
message.error.login.de=Falsche Bezeichner
message.error.login.it=Identificatori errati
message.error.traitment.fr=Erreur lors de l'envoi du document. Veuillez contacter votre administrateur
message.error.traitment.de=Fehler bei der Übermittlung des Dokumentes. Bitte kontaktieren Sie Ihren Administrator 
message.error.traitment.it=Errore di inserimento del documento. Prenda contatto con l’amministratore
message.error.type_document.fr=Type de fichier non autorisé
message.error.type_document.de=Dateityp nicht erlaubt
message.error.type_document.it=Tipo di documento non valido
message.display.name_unknown.active=1
message.display.name_unknown.fr=Assuré inconnu
message.display.name_unknown.it=Assicurato inesistente
message.display.name_unknown.de=Unbekannter Versicherter
message.display.name.active=1
message.error.ocr.number_incorrect.fr=Le numéro OCR est incorrect
message.error.ocr.number_incorrect.it=Le numéro OCR est incorrect
message.error.ocr.number_incorrect.de=Le numéro OCR est incorrect
message.error.ocr.number_notfound.fr=Ce numéro OCR n'est pas présent en GED
message.error.ocr.number_notfound.de=Ce numéro OCR n'est pas présent en GED
message.error.ocr.number_notfound.it=Ce numéro OCR n'est pas présent en GED
message.error.ocr.control_webai.fr=Ce numéro OCR n'est pas présent dans WEBAI
message.error.ocr.control_webai.it=Ce numéro OCR n'est pas présent dans WEBAI
message.error.ocr.control_webai.de=Ce numéro OCR n'est pas présent dans WEBAI
message.error.ocr.already_insert.fr=Ce numéro OCR a déjà été utilisé
message.error.ocr.already_insert.it=Ce numéro OCR a déjà été utilisé
message.error.ocr.already_insert.de=Ce numéro OCR a déjà été utilisé
message.error.ocr.size_error.fr=Le numéro OCR n'est pas correct formé (Suite de 12 ou 16 chiffres)
message.error.ocr.size_error.it=Le numéro OCR n'est pas correct formé (Suite de 12 ou 16 chiffres)
message.error.ocr.size_error.de=Le numéro OCR n'est pas correct formé (Suite de 12 ou 16 chiffres)
message.error.workflow.fr=Attention la valeur du champ Workflow ne peut être à NON si vous définissez un utilisateur dans le champ Destinataire

# Configuration AIRS DB
identity.field=NAME

# Configuration mapping types de documents
mapping.path=/opt/intairs/apache-tomcat-7.0.57/webapps/AirsDossier/xml/dt_mapping.csv

#
# WSDocSeries
################################################################################

# Deux valeurs de retour : id et value
webai.db.requete.get_assure=select trim(aivsweb.titierp.htlde1) || ' ' || trim(aivsweb.titierp.htlde2) as ID, trim(aivsweb.titierp.htlde1) || ' ' || trim(aivsweb.titierp.htlde2) as VALUE from aivsweb.titierp INNER JOIN aivsweb.tipavsp ON ( aivsweb.titierp.htitie = aivsweb.tipavsp.htitie ) where aivsweb.titierp.htpphy = '1' and aivsweb.titierp.htinac = '2' and aivsweb.tipavsp.hxnavs=CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(SUBSTR('##num_assure##',1,3),'.'),SUBSTR('##num_assure##',4,4)),'.'),SUBSTR('##num_assure##',8,4)),'.'),SUBSTR('##num_assure##',12,2))

# Extension fichier
file.extension.pdf=PDF
file.extension.office.word=DOC;DOCX
file.extension.office.excel=XLS;XLSX
file.extension.office.powerpoint=PPT;PPTX
file.extension.tif=TIF;TIFF

list.traduction.active=1
list.traduction.default=fr
list.profil.admin.id=13
list.group.id=10
list.type.id=11
list.profil.user.type_filter=34::35::36::37::38::39::40::41::42::43::44::45::46::47::48::49::50::51::52::53::54::55::56::57::58::59::60::61::62::63::64::65::66::67::68::69::70::71::72::73::74::75::76::77::78::79::80::81::82::83::84::85::86::87::88::89::90::91::92::93::94::95::96::97::98::99::100::101::102::103::104::105::106::107::108::109::110::111::112::113::114::115::116::117::118::119::120::121::122::123::124::125::126::127::128::129::130::131::132::133::134::135::136::137::138::139::140::141::142::143::144::145::146::147::148::149::150::151::152::153::154::155::156::157::158::159::160::161::162::163::164::165::166::167::168::169::170::171::172::173::174::175::176::177::178::179::180::181::182::183::184::185::186::187::188::189::190::191::192::193::194::196::197::198::199::200::201::202::203::204::205::206::207::208::209::210::211::212::213::214::215::216::217::218::219::220::221::222::223::224::225::226::227::228::229::230::250::251::252::253::254::255::256::257::258::259::260::261::262::263::264::265::266::267::268::269::270::271::272::273::274::275::276::278::279::280::281::282::283::284::285::286
list.profil.user.group_filter=13::14::15::16::17::18::19::20::21::22::23::25::26::27::28::29::30::31::32::33