## Utiliser ce fichier pour surcharger les clés du dictionnaire Francais pour les Images.
## Pour activer ce fichier, ne pas oublier de renommer le fichier (supprimer le premier '_')

# Logo affiché dans le pied de page
#img_logo=/custom/ui/img/votreLogo.png

image_product=/ui/courrierLight/img/header-logo.png
image_product2=/ui/courrierLight/img/header-logo2.png

logo_digitech_small=/ui/courrierLight/img/logo_digi.ico
icon_arrow_down=/ui/courrierLight/img/arrow_down.png
icon_close_small=/ui/courrierLight/img/close.png
icon_arrow_down_small=/ui/courrierLight/img/arrow_down_8x8.png

image_today=/ui/courrierLight/img/today.png

icon_refresh_small=/ui/courrierLight/img/action_refresh2_16x16.png
icon_download_small=/ui/courrierLight/img/action_download_12x12.png

icon_delegate=/ui/courrierLight/img/icon_delegate.png

icon_attachment_default_small=/ui/courrierLight/img/attachment_default_16x16.gif
icon_attachment_pdf_small=/ui/courrierLight/img/attachment_pdf_16x16.gif
icon_attachment_tif_small=/ui/courrierLight/img/attachment_tif_16x16.gif
icon_attachment_tiff_small=/ui/courrierLight/img/attachment_tif_16x16.gif
icon_attachment_jpg_small=/ui/courrierLight/img/attachment_jpg_16x16.gif
icon_attachment_jpeg_small=/ui/courrierLight/img/attachment_jpg_16x16.gif
icon_attachment_htm_small=/ui/courrierLight/img/attachment_htm_16x16.gif
icon_attachment_html_small=/ui/courrierLight/img/attachment_htm_16x16.gif
icon_attachment_doc_small=/ui/courrierLight/img/attachment_doc_16x16.gif
icon_attachment_docx_small=/ui/courrierLight/img/attachment_doc_16x16.gif
icon_attachment_xls_small=/ui/courrierLight/img/attachment_xls_16x16.gif
icon_attachment_xlsx_small=/ui/courrierLight/img/attachment_xls_16x16.gif
icon_attachment_ppt_small=/ui/courrierLight/img/attachment_ppt_16x16.gif
icon_attachment_pptx_small=/ui/courrierLight/img/attachment_ppt_16x16.gif
icon_attachment_eml_small=/ui/courrierLight/img/attachment_eml_16x16.gif
icon_attachment_txt_small=/ui/courrierLight/img/attachment_txt_16x16.gif
icon_attachment_odt_small=/ui/courrierLight/img/attachment_odt_16x16.gif
icon_attachment_odp_small=/ui/courrierLight/img/attachment_odp_16x16.gif
icon_attachment_ods_small=/ui/courrierLight/img/attachment_ods_16x16.gif

icon_favorites_tracked_small=/ui/courrierLight/img/favorites_tracked_16x16.png
icon_favorites_small=/ui/courrierLight/img/favorites_16x16.png

status_error=/ui/courrierLight/img/alert_error.png
status_warn=/ui/courrierLight/img/alert_warn.png
status_info=/ui/courrierLight/img/alert_info.png

checker_error=/ui/courrierLight/img/status_failure.png
checker_error_small=/ui/courrierLight/img/status_failure_small.png
checker_warn=/ui/courrierLight/img/status_warning.png
checker_warn_small=/ui/courrierLight/img/status_warning_small.png
checker_success=/ui/courrierLight/img/status_success.png
checker_success_small=/ui/courrierLight/img/status_success_small.png
checker_info=/ui/courrierLight/img/status_info.png
checker_info_small=/ui/courrierLight/img/status_info_small.png

notification_error=/ui/courrierLight/img/notif_error.jpg
notification_warn=/ui/courrierLight/img/notif_warn.jpg
notification_info=/ui/courrierLight/img/notif_info.jpg
notification_success=/ui/courrierLight/img/notif_success.jpg

icon_waiting01=/ui/courrierLight/img/waiting01.gif
icon_loading01=/ui/courrierLight/img/loading_01.gif
icon_loading_small=/ui/courrierLight/img/loading_16x16.gif

icon_warn_small=/ui/courrierLight/img/icon_warn_12x12.png
icon_warn_medium=/ui/courrierLight/img/warning_medium.gif
icon_error_medium_anim=/ui/courrierLight/img/error_medium_anim.gif
icon_warn_medium_anim=/ui/courrierLight/img/warning_medium_anim.gif

actions_separator=/ui/courrierLight/img/woodstock/actions_separator.gif

waiting_request=/ui/courrierLight/img/ajax-loader.gif
waiting_request2=/ui/courrierLight/img/ajax-loader2.gif
waiting_request_modalPanel=/ui/courrierLight/img/ajax-loader_modalPanel.gif
waiting_request_table=/ui/courrierLight/img/ajax-loader_table.gif

btn_up=/ui/courrierLight/img/btn_up01.png
btn_refresh=/ui/courrierLight/img/btn_refresh01.png

icon_treeNode_favorite_tracked=/ui/courrierLight/img/treeNode_favorite02.png

## Menu Item ##
icon_menuItem_flowSelected=/ui/courrierLight/img/check01.png

## Table ##
table_sort_clear=/ui/courrierLight/img/sort_clear.gif
table_reset_state=/ui/airs/img/reset_state.gif
table_gotToFirst=/ui/courrierLight/img/goToFirst.png
table_gotToFirst_off=/ui/courrierLight/img/goToFirst_off.png
table_gotToLast=/ui/courrierLight/img/goToLast.png
table_gotToLast_off=/ui/courrierLight/img/goToLast_off.png
table_previous=/ui/courrierLight/img/previous.png
table_previous_off=/ui/courrierLight/img/previous_off.png
table_next=/ui/courrierLight/img/next.png
table_next_off=/ui/courrierLight/img/next_off.png
table_sorting_off=/ui/courrierLight/img/sorting_off.png
table_sorting_asc=/ui/courrierLight/img/sorting_asc.png
table_sorting_desc=/ui/courrierLight/img/sorting_desc.png

## Login ##
login_image_product=/ui/courrierLight/img/login-logo.png
login_image_connect=/ui/courrierLight/img/connexion.png

icon_1x1=/ui/courrierLight/img/1x1.gif

icon_minimize=/ui/courrierLight/img/minimize.png
icon_maximize=/ui/courrierLight/img/maximize.png

## Home ##
icon_search_large=/ui/courrierLight/img/module_search_64x64.png
icon_searchResult_large=/ui/courrierLight/img/module_resultsimple_64x64.png
icon_reporting_large=/ui/courrierLight/img/module_report_64x64.png
icon_userManagement_large=/ui/courrierLight/img/module_gestuser_64x64.png
icon_indexing_large=/ui/courrierLight/img/module_gestindex_64x64.png
icon_createDocument_large=/ui/courrierLight/img/add_doc_64x64.png
icon_editDocument_large=/ui/airs/img/action_modif_64x64.png
icon_admin_large=/ui/courrierLight/img/module_administrer_64x64.png
icon_admin_document_large=/ui/courrierLight/img/doc_admin_64x64.png
icon_admin_wizard_large=/ui/courrierLight/img/config_wizard_64x64.png
icon_admin_licenseManage_graph=/ui/courrierLight/img/module_gestuser_16x16.png
icon_admin_licenseManager_large=/ui/courrierLight/img/module_gestuser_64x64_over.png
icon_admin_annotation_large=/ui/courrierLight/img/pj_annotation_64x64.png

icon_refreshBasket_small=/ui/courrierLight/img/action_refresh_16x16.png
icon_displayBasket_small=/ui/courrierLight/img/action_display_16x16.png
icon_searchResult_small=/ui/courrierLight/img/action_display_16x16.png
icon_search_small=/ui/courrierLight/img/action_search_16x16.png

btn_search01=/ui/courrierLight/img/search_btn01.png

## Search Result - infos ##
icon_unlocked_medium=/ui/courrierLight/img/info_doc_notlocked_16x16.png
icon_lockedByMe_medium=/ui/courrierLight/img/info_mylock_doc_16x16.png
icon_lockedByOther_medium=/ui/courrierLight/img/info_doc_locked_16x16.png
icon_comments_medium=/ui/courrierLight/img/info_comments_16x16.png

## Search Result - Action ##
icon_lock_medium=/ui/courrierLight/img/action_lock_doc_16x16.png
icon_unlock_medium=/ui/courrierLight/img/action_unlock_doc_16x16.png
icon_display_tree_view_medium=/ui/courrierLight/img/displayr_arborescence_16x16.png
icon_display_unit_view_medium=/ui/courrierLight/img/dsiplay-vue-unitaire_16x16.png
icon_edit_unit_view_medium=/ui/courrierLight/img/edit-vue-unitaire_16x16.png

## Update ##
icon_save_large=/ui/courrierLight/img/save_32x32.png
icon_edit_large=/ui/courrierLight/img/action_modif_32x32.png
icon_delete_large=/ui/courrierLight/img/del_32x32.png
icon_create_large=/ui/courrierLight/img/add_doc_32x32.png
icon_mail_large=/ui/courrierLight/img/action_send_mail_32x32.png
icon_clipboard_large=/ui/courrierLight/img/action_clipboard_32x32.png
icon_display_attachment_small=/ui/courrierLight/img/action_display_16x16.png
icon_edit_attachment_small=/ui/courrierLight/img/action_editAttachment_16x16.png
icon_display_document_small=/ui/courrierLight/img/action_display_16x16.png
icon_save_small=/ui/courrierLight/img/save_16x16.png
icon_edit_small=/ui/courrierLight/img/action_modif_16x16.png
icon_admin_small=/ui/courrierLight/img/module_administrer_16x16.png
icon_delete_small=/ui/courrierLight/img/del_16x16.png
icon_pushpin_on_large=/ui/courrierLight/img/pushpin_active_32x32.png
icon_pushpin_off_large=/ui/courrierLight/img/pushpin_desactive_32x32.png
icon_addToFavorites_large=/ui/courrierLight/img/action_addToFavorites_32x32.png
icon_showBookmarks_large=/ui/courrierLight/img/action_showBookmarks_32x32.png

## Action Workflow ##
icon_startWorkflow_large=/ui/courrierLight/img/instance_add_32x32.png
icon_processTask_large=/ui/courrierLight/img/instance_valider_32x32.png
icon_workflowAirs_large=/ui/courrierLight/img/instance_valider_32x32.png
icon_customAction_large=/ui/courrierLight/img/action_custom_32x32.png
icon_exportAction_large=/ui/courrierLight/img/action_customExport_32x32.png
icon_customAction_display_fsCourrier=/ui/courrierLight/img/action_fiche_courrier.png
icon_pjAction_small=/ui/courrierLight/img/action_custom_16x16.png
icon_viewer_pjAction=/ui/courrierLight/img/viewer/action_custom.gif

# do not remove 
icon_ask_visa=/ui/courrierLight/img/instance_terminer_32x32.png

task_Delegate=/ui/courrierLight/img/instance_attrib_organism_32x32.png
task_Attribuer=/ui/courrierLight/img/instance_attrib_personne_32x32.png
task_Mettre_en_attente=/ui/courrierLight/img/instance_attente_32x32.png
task_Clore=/ui/courrierLight/img/instance_terminer_32x32.png

## Action bar ##
action_sec_task_validate=/ui/courrierLight/img/actionBar/sec_validate.png
action_sec_task_Delegate=/ui/courrierLight/img/actionBar/sec_delegate.png
action_sec_task_Attribuer=/ui/courrierLight/img/actionBar/sec_assign.png
action_sec_task_Mettre_en_attente=/ui/courrierLight/img/actionBar/sec_stack.png
action_sec_task_Clore=/ui/courrierLight/img/actionBar/sec_close.png

icon_selectDocument_medium=/ui/courrierLight/img/action_display_16x16.png

## Report ##
icon_display_pdf_small=/ui/courrierLight/img/action_display-report_PDF_16x16.png
icon_display_html_small=/ui/courrierLight/img/action_display-report_HTML_16x16.png


## Administration ##
icon_close_small_admin=/ui/courrierLight/img/close.png

## Advanced search ##
icon_addLocution=/ui/courrierLight/img/action_addloc_32x32.png
icon_addOperatorAnd=/ui/courrierLight/img/action_addET_32x32.png
icon_addOperatorOr=/ui/courrierLight/img/action_addOU_32x32.png
icon_addOperatorNot=/ui/courrierLight/img/action_addSAUF_32x32.png
icon_searchaction=/ui/courrierLight/img/module_search_32x32.png
icon_addRightParenthesis=/ui/courrierLight/img/action_addparD_32x32.png
icon_addLeftParenthesis=/ui/courrierLight/img/action_addparG_32x32.png

## Picker ##
icon_picker_calendar=/ui/courrierLight/img/calendar.png
icon_picker_backward=/ui/courrierLight/img/backward.png
icon_picker_up=/ui/courrierLight/img/up.png
icon_picker_down=/ui/courrierLight/img/down.png
icon_picker_search=/ui/courrierLight/img/search.png
icon_picker_authorityList=/ui/courrierLight/img/search_authorityList.png
icon_picker_authorityList_tree=/ui/courrierLight/img/search_authorityList_tree.png
icon_picker_organization=/ui/courrierLight/img/search_organization.png
icon_picker_user=/ui/courrierLight/img/search_user.png
icon_picker_save=/ui/courrierLight/img/save_16x16.png
icon_picker_del=/ui/courrierLight/img/del_16x16.png
icon_picker_correspondent_add=/ui/courrierLight/img/addCorrespondent_16x16.png
icon_picker_correspondent_edit=/ui/courrierLight/img/editCorrespondent_16x16.png
icon_picker_correspondent_delete=/ui/courrierLight/img/delCorrespondent_16x16.png

icon_picker_add=/ui/courrierLight/img/addCorrespondent_16x16.png
icon_picker_edit=/ui/courrierLight/img/editCorrespondent_16x16.png
icon_picker_delete=/ui/courrierLight/img/delCorrespondent_16x16.png

## Footer ##
img_border_right=/ui/courrierLight/img/footer-r.gif
img_border_left=/ui/courrierLight/img/footer-l.gif
img_logo=/ui/courrierLight/img/footer-logo.gif

## Courrier ##
icon_treeNode_courrier_in=/ui/courrierLight/img/treeNode_courrier_in_16x16.png
icon_treeNode_courrier_out=/ui/courrierLight/img/treeNode_courrier_out_16x16.png

## GRC ##
icon_treeNode_grc=/ui/courrierLight/img/treeNode_grc_16x16.png

## RECYCLEBIN ##
icon_restoreDocument_small=/ui/courrierLight/img/doc_restore_24x24.png
icon_removeDocument_small=/ui/courrierLight/img/doc_remove_24x24.png


## Administration Module ##
###########################
icon_admin_copy=/ui/courrierLight/img/page_copy.png
icon_admin_paste=/ui/courrierLight/img/page_paste.png
icon_admin_save=/ui/courrierLight/img/page_save.png

icon_admin_diagnostic_large=/ui/courrierLight/img/icon_diagnostic_64x64.png
icon_admin_document_locked_large=/ui/courrierLight/img/doc_locked_liste_64x64_over.png
icon_admin_courrier_large=/ui/courrierLight/img/module_courrier_64x64.png
icon_admin_airs_large=/ui/courrierLight/img/module_airs_64x64.png
icon_admin_pop_large=/ui/courrierLight/img/module_gestuser_64x64.png
icon_admin_task_large=/ui/courrierLight/img/task_planning_64x64.png
icon_admin_cache_large=/ui/courrierLight/img/module_cache_64x64.png
icon_admin_wkf_large=/ui/courrierLight/img/module_wkf_64x64.png
icon_admin_import_export_large=/ui/courrierLight/img/module_importexport_64x64.png
admin_icon_createDocument_annotation_large=/ui/courrierLight/img/add_doc_64x64.png
img_logo_footer=/ui/courrierLight/img/footer-logo.gif

icon_admin_preview=/ui/courrierLight/img/action_display_16x16.png
icon_admin_download=/ui/courrierLight/img/action_custom_16x16.png
icon_admin_merge=/ui/courrierLight/img/displayr_arborescence_16x16.png
icon_admin_replace=/ui/courrierLight/img/edit-vue-unitaire_16x16.png
icon_admin_test=/ui/courrierLight/img/instance_valider_16x16.png

## Flow ##
icon_admin_flow_showLinkContentTypes=/ui/courrierLight/img/showLinkContentTypes_16x16.png
icon_admin_flow_showExtraFilters=/ui/courrierLight/img/showExtraFilters_16x16.png


icon_validate=/custom/ui/img/votreImage.png
icon_response=/custom/ui/img/response.png
icon_restore=/custom/ui/img/restore.png
icon_visa=/custom/ui/img/visa.png
icon_generate=/custom/ui/img/generate.png
icon_reset=/custom/ui/img/reset.gif
icon_closing=/custom/ui/img/closing.png
