######################
# Configuration Wizard
######################
configuration.login=Admin
configuration.password=Admin

##########
# Workflow
##########
workflow.cacheSize=20000
workflow.database.oracleUsed=true

######
# User
######
# Enables the user role management
user.roleEnabled=false
# Synchronizes the user preferences with the AIRS User
user.airsDataSynchronized=false

#################
# Personal Space
#################
personalSpace.clipboardSize=10
personalSpace.historyDocumentSize=10
personalSpace.historySearchSize=10
personalSpace.historyAttachmentSize=10

######
# Misc
######
misc.notificationDaysNumberBeforePasswordExpiration=20
misc.deactivationSortingSearchResultNumber=5000
misc.basketShortTitleSize=50
misc.displayedBookmarksMaxNumber=500
misc.lazyModalPanelEnabled=false
# misc.debugMessageBundleKey=true

# Possible values are: BLANK, FIELD_CODE and FIELD_DESCRIPTION
misc.hierarchicalTreeNodeVariableEmptyMode=FIELD_CODE

# Defines the time interval (milliseconds) between two Poll Ajax request
misc.applicationPollEnabled=true
misc.applicationPollInterval=10000

# Defines the session timeout interval (milliseconds)
# 2h00
misc.sessionTimeout=7200000

# Defines the number of Tomcat sessions enabled by user
# -1 defines unlimited sessions by user
# misc.numberOfSessionsByUser=-1

# Defines the document auto-lock timeout (milliseconds)
# 2h00
misc.autoLockedDocumentTimeout=7200000

# Defines if the notification messages have time out
misc.notificationMessageTimeoutEnabled=true

# Defines the IE compatibility version
misc.compatibilityVersion.IE=7

# Defines the number of attachments which can be added in creation pages
document.creation.max.file.quantity=5

#####
# SSO
#####
# Defines the type of SSO to use. Possible values are: SPNEGO, APACHE
#sso.type=

#########
# Display
#########
display.attachmentLayout.defaultWidth=600
display.attachmentLayout.defaultHeight=300
display.attachmentLayout.defaultWidthRatio=0.4
display.attachmentLayout.defaultHeightRatio=0.33

#########
# Debug script: allow to compile script on runtime
#########
script.debug=false
