############################################################################
#									   #
#	Fichier de configuration pour le WEBSERVICE WSDocument		   #
#									   #
############################################################################

# Index du type de contenu Doc Affilie
############################################################################
FIELD_LIST_INOUTDOCS=AL_IN_OUT_DOC
FIELD_ORGANISATION=AL_ORGA_WKF
FIELD_SERVICE=AL_SERVICE
FIELD_DATE_ECHEANCE=D_ECHEANCE
FIELD_TAXATEUR=U_TAXATEUR
FIELD_TITRE=AL_TITRE
FIELD_PRENOM=PRENOM_AFF
FIELD_NOM=NOM_AFF
FIELD_NSS=N_NSS
FIELD_NIP=N_AFF
FIELD_ADRESSE=ADRESSE_AFF
FIELD_CATEGORIE=AL_CATEGORIE
FIELD_CAISSE=AL_CAISSE
FIELD_TYPE_DOC=AL_TYPE
FIELD_COMMENTAIRE=COMMENTAIRE
FIELD_STATE_WORKFLOW=AL_STATUT
FIELD_FILENAME=FILENAME
FIELD_STATE=STATUT_WORKFLOW

FIELD_DESCRIPTION=COM
FIELD_DATE_ARCHIVAGE=D_ARCHIVAGE

# Valeur des listes d'autorité
############################################################################
VALUE_LIST_OUTINT=12
VALUE_LIST_TITLE_MME=93
VALUE_LIST_TITLE_MR=94
VALUE_LIST_ACONTROLER=70
VALUE_LIST_ADISTRIBUER=71
VALUE_LIST_ATRAITER=74
VALUE_LIST_ARCHIVER=77
VALUE_LIST_SERVICE_FINANCE=775
VALUE_LIST_SERVICE_PC=30
VALUE_LIST_EXLPOS1=776
VALUE_LIST_CAISSE_CCVD=3
# Id type de document pour les documents venant de Doc.Office
VALUE_LIST_TYPE_INPUT=705
VALUE_LIST_CORRESPONDANCE=8

# ID des listes d'autorité
############################################################################
ID_AL_CATEGORIE=3
ID_AL_CAISSE=2
ID_AL_TYPE_DOC=9
ID_AL_SERVICE=5

# Mapping Organisation <-> Niveau de secret
############################################################################
organisation.secret.1=200
organisation.secret.2=300
organisation.secret.3=700
organisation.secret.4=700
organisation.secret.5=800
organisation.secret.6=800
organisation.secret.7=600
organisation.secret.8=200
organisation.secret.9=200
organisation.secret.10=200
organisation.secret.11=300
organisation.secret.12=700
organisation.secret.13=400
organisation.secret.14=200
organisation.secret.15=200
organisation.secret.16=100
organisation.secret.17=100
organisation.secret.18=100
organisation.secret.19=200
organisation.secret.20=200
organisation.secret.21=900
organisation.secret.22=300
organisation.secret.23=300
organisation.secret.24=300
organisation.secret.25=200
organisation.secret.28=300
organisation.secret.30=1000
organisation.secret.31=200

# Mapping Organisation <-> Service
############################################################################
; organisation.service.1=24
; organisation.service.2=34
; organisation.service.3=25
; organisation.service.4=26
; organisation.service.5=27
; organisation.service.6=28
; organisation.service.7=35
; organisation.service.8=24
; organisation.service.10=24
; organisation.service.11=34
; organisation.service.12=25
; organisation.service.13=36
; organisation.service.14=24
; organisation.service.15=695
; organisation.service.16=30
; organisation.service.17=31
; organisation.service.18=32
; organisation.service.19=24
; organisation.service.20=24
; organisation.service.21=33
; organisation.service.22=34
; organisation.service.23=37
; organisation.service.24=38
; organisation.service.25=696
; organisation.service.26=41
; organisation.service.28=39
; organisation.service.30=775

# Mapping Service
#######################################################################
service.CTC=AC
service.CTE=AC
service.PCC=PC
service.RTC=RENTES
service.RCC=REC
service.IJ=IJAI
service.CTC=AC
service.RENTES_API=RENTES_API_AI
service.IM=AC

# Informations sur le mapping des codes services avec le délai défini 
# avant lequel leurs documents WORD seront convertis en PDF                                                 
#######################################################################
#AC
auto.convert.delay.1=90
#ACC. BIL.
auto.convert.delay.2=5
#AF PSA
auto.convert.delay.4=30
#AF
auto.convert.delay.3=30
#ALMAT_CANT
auto.convert.delay.5=5
#AMF
auto.convert.delay.6=5
#FM
auto.convert.delay.12=5
#REC
auto.convert.delay.21=5
#RENTES
auto.convert.delay.22=5
#APG MILITAIRES
auto.convert.delay.7=5
#IJAI
auto.convert.delay.13=5
#RENTES_AI
auto.convert.delay.23=5
#RENTES_AVS
auto.convert.delay.24=5
#RENTES_API
auto.convert.delay.28=5
#SCAN
auto.convert.delay.26=5
#CCVD
auto.convert.delay.29=5
#PC
auto.convert.delay.16=5
#PCF
auto.convert.delay.17=5
#PCG
auto.convert.delay.18=14
#JU
auto.convert.delay.15=14
#REV
auto.convert.delay.25=5
#ESTIMATIONS
auto.convert.delay.11=5
#IM
auto.convert.delay.14=5
#PSA
auto.convert.delay.20=5
#PCI
auto.convert.delay.19=5
#CTE
auto.convert.delay.10=5
#Ci-CA
auto.convert.delay.8=5
#FINANCE
auto.convert.delay.30=5
#Defaut
auto.convert.delay.defaut=5

# Mapping Organisation <-> Service
############################################################################
organisation.service.1=24
organisation.service.2=34
organisation.service.3=25
organisation.service.4=26
organisation.service.5=27
organisation.service.6=28
organisation.service.7=35
organisation.service.8=24
organisation.service.10=24
organisation.service.12=25
organisation.service.13=36
organisation.service.14=24
organisation.service.15=695
organisation.service.16=30
organisation.service.17=31
organisation.service.18=32
organisation.service.19=24
organisation.service.20=24
organisation.service.21=33
organisation.service.22=34
organisation.service.23=37
organisation.service.24=38
organisation.service.25=696
organisation.service.26=41
organisation.service.28=39
organisation.service.30=775
organisation.service.31=24

# DB Globaz
############################################################################

DB_GLOBAZ_CLASS = com.ibm.as400.access.AS400JDBCDriver
DB_GLOBAZ_URL = jdbc:as400://chclapr1
DB_GLOBAZ_USERNAME = digitech
DB_GLOBAZ_PASSWORD = avs_022
DB_GLOBAZ_CODE_TITLE_MR = 502001
DB_GLOBAZ_CODE_TITLE_MME = 502002
DB_GLOBAZ_REQUEST_GET_IDENTITY_BY_NAFF = SELECT HTTTTI, HTLDE1, HTLDE2 FROM CCVDPRD.TITIERP where CCVDPRD.TITIERP.HTITIE=?
DB_GLOBAZ_REQUEST_GET_NSS_BY_NAFF = SELECT HXNAVS FROM CCVDPRD.TIPAVSP WHERE CCVDPRD.TIPAVSP.HTITIE=?
DB_GLOBAZ_REQUEST_GET_LISTS_ADRESS_BY_NAFF = SELECT DISTINCT LEFT(TRIM(ccvdprd.tilocap.hjnpa),4) CONCAT ' ' CONCAT TRIM(ccvdprd.tilocap.hjloca) FROM ccvdprd.titierp INNER JOIN ccvdprd.tipersp  ON ( ccvdprd.tipersp.htitie = ccvdprd.titierp.htitie ) INNER JOIN ccvdprd.tipavsp  ON ( ccvdprd.tipavsp.htitie = ccvdprd.titierp.htitie ) LEFT OUTER JOIN ccvdprd.tiaadrp ON ( ccvdprd.tiaadrp.htitie = ccvdprd.titierp.htitie AND heiadr = heiaau AND hettad = 508008 AND hfiapp = 519004 AND heidex = '' AND ( ( 20110505 BETWEEN heddad AND hedfad ) OR ( hedfad = 0 AND heddad <= 20110505 ) ) AND hfiapp <> 519013 AND hfiapp <> 519014 ) LEFT OUTER JOIN ccvdprd.tiadrep ON ( ccvdprd.tiaadrp.haiadr = ccvdprd.tiadrep.haiadr ) LEFT OUTER JOIN ccvdprd.tilocap ON ( ccvdprd.tiadrep.hjiloc = ccvdprd.tilocap.hjiloc ) LEFT OUTER JOIN ccvdprd.tipaysp  ON ( ccvdprd.tilocap.hnipay = ccvdprd.tipaysp.hnipay ) WHERE ccvdprd.titierp.htitie=?
#DB_GLOBAZ_REQUEST_GET_ADRESS_BY_NAFF = SELECT replace(trim(coalesce(trad_typ.pcolut,'')),'¬','''') as TYPE, tiers.htitie as NIP, replace(trim(coalesce(trad_dom.pcolut,'')),'¬','''') as DOMAINE, replace(trim(coalesce(trad_titre.pcolut,'')),'¬','''') as ADR1, replace(trim(tiers.htlde1) concat ' ' concat trim(tiers.htlde2),'¬','''') as ADR2, replace(adr.haatte,'¬','''') as ADR3, case when length(trim(adr.HACPOS))>0 then 'Case postale ' concat trim(adr.HACPOS) else '' end as ADR4, replace(trim(adr.harue),'¬','''') concat ' ' concat trim(adr.hanrue) AS ADR5, case when loca.hnipay=100 then left(loca.hjnpa,4) concat ' ' concat replace(trim(loca.hjloca),'¬','''') else loca.hjnpa concat ' ' concat replace(trim(loca.hjloca),'¬','''') end AS ADR6 from ccvdprd.titierp tiers left join ccvdprd.fwcoup trad_titre on trad_titre.pcosid=tiers.htttti and trad_titre.plaide='F' left join ccvdprd.tiaadrp avadr on avadr.htitie=tiers.htitie and avadr.hedfad=0 inner join ccvdprd.fwcoup trad_dom on trad_dom.pcosid=avadr.hfiapp and trad_dom.plaide='F' inner join ccvdprd.fwcoup trad_typ on trad_typ.pcosid=avadr.hettad and trad_typ.plaide='F' inner join ccvdprd.tiadrep adr on adr.haiadr=avadr.haiadr inner join ccvdprd.tilocap loca ON loca.hjiloc=adr.hjiloc where tiers.htitie= ?
DB_GLOBAZ_REQUEST_GET_ADRESS_BY_NAFF = SELECT case when loca.hnipay=100 then left(loca.hjnpa,4) concat ' ' concat replace(trim(loca.hjloca),'¬','''') else loca.hjnpa concat ' ' concat replace(trim(loca.hjloca),'¬','''') end AS ADR6 from ccvdprd.titierp tiers left join ccvdprd.fwcoup trad_titre on trad_titre.pcosid=tiers.htttti and trad_titre.plaide='F' left join ccvdprd.tiaadrp avadr on avadr.htitie=tiers.htitie and avadr.hedfad=0 inner join ccvdprd.fwcoup trad_dom on trad_dom.pcosid=avadr.hfiapp and trad_dom.plaide='F' inner join ccvdprd.fwcoup trad_typ on trad_typ.pcosid=avadr.hettad and trad_typ.plaide='F' inner join ccvdprd.tiadrep adr on adr.haiadr=avadr.haiadr inner join ccvdprd.tilocap loca ON loca.hjiloc=adr.hjiloc where tiers.htitie= ?

# Flags de traitement
############################################################################
TYPE_DOC_OFFICE=Doc.Office
FLAG_WORKFIN=WORKFIN
DOC_EXCEL_WORKFLOW_FINANCE=2
DOC_WORD_WORKFLOW_FINANCE=1

DOC_PDF_EXTENSION=PDF
DOC_WORD_EXTENSION=DOC::DOCX
WORD_FIELD_COMMENT=COMMENTS
WORD_FIELD_SERVICE=DOCINF/DDDEPID

# Akazi
############################################################################
WORKFLOW_AKAZI_PROCESS_NAME=flow_ccvd

# Mapping Akazi
############################################################################
# mapping code orga taxateur et code workflow correspondant
workfow.service.RENTES_AVS=REN
workfow.service.RENTES_AI=REN
workfow.service.RENTES_API=REN
workfow.service.RENTES_AVS=REN
workfow.service.RENTES_1=REN
workfow.service.RENTES_2=REN
workfow.service.RENTES_3=REN
workfow.service.RENTES_4=REN
workfow.service.JU=REN
workfow.service.ACCORDS_BILATERAUX=REN
workfow.service.ESTIMATIONS=REN
workfow.service.RENTES=REN
workfow.service.APG_MILITAIRES=REN
workfow.service.IJAI=REN
workfow.service.AMF=AMF
workfow.service.ALMAT_CANT=AMF
workfow.service.PSA=AC
workfow.service.AC=AC
workfow.service.PCI=AC
workfow.service.CTP=AC
workfow.service.CTC=AC
workfow.service.CTA=AC
workfow.service.CI-CA=AC
workfow.service.IM=AC
workfow.service.PSA=AC
workfow.service.CTE=CTE
workfow.service.EMP=CTE
workfow.service.REV=AC
workfow.service.AF=AF
workfow.service.AF_PSA=AF PSA
workfow.service.AF\ PSA=AF PSA
workfow.service.AMF=AMF
workfow.service.IJ=IJAI
workfow.service.PC=PC
workfow.service.PCF=PC
workfow.service.PCG=PC
workfow.service.REC=REC
workfow.service.PSA_1=AC
workfow.service.PSA_2=AC