## Use this file to overload the english dictionary keys for the Images. 
## To activate this file, don't forget to rename it (remove the leading '_')

#icon_search_large=./custom/ui/img/yourImage.png
iconEcheance=./custom/ui/img/CCVD_due_32x32.png
iconPDF=./custom/ui/img/CCVD_word2pdf_32x32.png
iconDossierPDF=./custom/ui/img/CCVD_pdf_32x32.png
iconSynchro=./custom/ui/img/CCVD_sync_32x32.png
iconNewWord=./custom/ui/img/CCVD_new_word_32x32.png
iconReminder=./custom/ui/img/CCVD_new_word_rappel_32x32.png
iconArchivePDFEcheance=./custom/ui/img/CCVD_word2pdftimer_32x32.png

#images workflow
action_sec_task_NSS_cree=./custom/ui/img/nss.png
action_sec_task_NIP_cree=./custom/ui/img/nip.png
action_sec_task_Archive=./custom/ui/img/archive.png
action_sec_task_En_traitement=./custom/ui/img/en_traitement.png
action_sec_task_En_attente_de_reponse=./custom/ui/img/en_attente_de_reponse.png
action_sec_task_Urgent=./custom/ui/img/urgent.png
action_sec_task_Mutation_en_cours=./custom/ui/img/mutation_en_cours.png
action_sec_task_A_controler=./custom/ui/img/a_controler.png
action_sec_task_DEM_a_traiter=./custom/ui/img/dem_a_traiter.png
action_sec_task_En_attente_affil_PCI=./custom/ui/img/en_attente_affil_pci.png
action_sec_task_En_attente_affil_EMP=./custom/ui/img/en_attente_affil_emp.png
action_sec_task_En_attente_affil_PSA=./custom/ui/img/en_attente_affil_psa.png
action_sec_task_Mail_a_indexer./custom/ui/img/mail.png
action_sec_task_Adresse_creee=./custom/ui/img/adresse.png
action_sec_task_Indexation_corrigee=./custom/ui/img/index_corrigee.png
action_sec_task_Transfert_CI-CA=./custom/ui/img/instance_attrib_organism_32x32.png
action_sec_task_Reponse_Centrale_OK=./custom/ui/img/nss.png
action_sec_task_Non=./custom/ui/img/reject2.png
action_sec_task_oui=./custom/ui/img/checked_valid2.png
action_sec_task_A_valider=./custom/ui/img/a_valider.png
action_sec_task_Refuse_En_attente_de_reponse=./custom/ui/img/en_attente_de_reponse.png
action_sec_task_Refuse_Urgent=./custom/ui/img/urgent.png
action_sec_task_Refuse=./custom/ui/img/reject2.png
action_sec_task_Rejete=./custom/ui/img/reject2.png
action_sec_task_Reponse_obtenue=./custom/ui/img/mail.png
action_sec_task_Reponse_Centrale_OK=./custom/ui/img/mail.png
action_sec_task_Mail_indexe=./custom/ui/img/index_corrigee.png
action_sec_task_Valide=./custom/ui/img/checked_valid2.png
action_sec_task_NSS_a_creer=./custom/ui/img/nss.png

