## Utiliser ce fichier pour surcharger les clés du dictionnaire Francais pour les Pages.
## Pour activer ce fichier, ne pas oublier de renommer le fichier (supprimer le premier '_')

deleteDocumentPanel=./custom/ui/jsp/customDeleteDocumentPanel.jsp
modalPanelCustomAction=./custom/ui/jsp/modalPanelCustomAction.jsp
modalPanelApplet=./custom/ui/jsp/modalPanelApplet.jsp
modalPanelGetFile=./custom/ui/jsp/modalPanelGetFile.jsp
modalPanelSelectUser=./custom/ui/jsp/modalPanelSelectUser.jsp
modalPanelSelectService=./custom/ui/jsp/modalPanelSelectService.jsp
modalPanelReminderApplet=./custom/ui/jsp/modalReminderPanelApplet.jsp
modalPanelAddNote=./custom/ui/jsp/modalPanelAddNote.jsp
modalPanelSelectUserOnly=./custom/ui/jsp/modalPanelSelectUserOnly.jsp
modalPanelSearchFromSimpleView=./custom/ui/jsp/modalPanelSearchFromSimpleView.jsp
modalPanelWkf=./custom/ui/jsp/workflow/modalPanelWkf.jsp
modalPanelWkfWithComment=./custom/ui/jsp/workflow/modalPanelWkfWithComment.jsp
modalPanelSetNIP=./custom/ui/jsp/modalPanelSetNIP.jsp
modalPanelPCIPSAWkf=./custom/ui/jsp/workflow/modalPanelPCIPSAWkf.jsp
modalPanelDuplication=./custom/ui/jsp/modalPanelDuplication.jsp
modalPanelSetAvisMutation=./custom/ui/jsp/modalPanelSetAvisMutation.jsp
modalPanelWkfAvisMutation=./custom/ui/jsp/workflow/modalPanelWkfAvisMutation.jsp
modalPanelSetInformationsAvisMutation=./custom/ui/jsp/modalPanelSetInformationsAvisMutation.jsp
modalPanelControlAvisMutation=./custom/ui/jsp/modalPanelControlAvisMutation.jsp
