[[_21_Shortcuts]]
== Raccourcis

Cette section détaille certains raccourcis clavier utilisables dans l’application :

=== Raccourcis globaux

L’ensemble des actions personnalisées peut être associé à un raccourci clavier (dont la valeur dépend de votre paramétrage).

=== Vue Réponse et Résultat

* Les flèches haut et bas permettent de naviguer entre les éléments :
* Il est possible de télécharger la pièce jointe active avec le raccourci kbd:[Ctrl+Alt+D] (valeur par défaut).
* Il est possible de réaliser des actions d’interactions tel que valider ou appliquer via le raccourci kbd:[Ctrl+Entrée].
Sur la page de *Création*,
kbd:[Ctrl+Entrée] permet la création d’un nouveau document.

==== Visionneuse

Vous pouvez utiliser les raccourcis clavier suivant durant la consultation de document dans la *visionneuse* :

* Flèche droite kbd:[→] : affiche la page suivante du document.
* Flèche gauche kbd:[←] : affiche la page précédente du document.
* Touche plus kbd:[+] : augmente le niveau de zoom d’un palier.
* Touche moins kbd:[-] : diminue le niveau de zoom d’un palier.

<<<