MAIL_NOTIFICATION_ENABLED = true

PROFILE_CODE_ADMIN = DOS_ADMIN
PROFILE_CODE_DIR = DOS_DIRECTION
PROFILE_CODE_GEST = DOS_GESTIONNAIRE

CONTENT_TYPE_COU_COURRIER_IN = COU_COURRIER_IN
CONTENT_TYPE_COU_COURRIER_OUT = COU_COURRIER_OUT
CONTENT_TYPE_COU_REPONSE = COU_REPONSE

ATTACHMENT_TYPE_COURRIER_IN = COU_RECU
ATTACHMENT_TYPE_COURRIER_OUT = COU_EMIS

LINK_COURRIER_REPONSE = courrier-reponse

FIELD_CODE_U_CREAT = U_CREAT
FIELD_CODE_N_CHRONO = N_CHRONO
FIELD_CODE_T_TYPE = T_TYPE
FIELD_CODE_E_LU = E_LU
FIELD_CODE_T_ETAT_COURRIER = T_ETAT_COURRIER
FIELD_CODE_T_ETAT_VISA = T_ETAT_VISA
FIELD_CODE_U_PROPRIETAIRE = U_PROPRIETAIRE
FIELD_CODE_O_PROPRIETAIRE = O_PROPRIETAIRE
FIELD_CODE_U_VALIDEUR = U_VALIDEUR
FIELD_CODE_U_VISEUR = U_VISEUR
FIELD_CODE_D_VALIDATION = D_VALIDATION
FIELD_CODE_D_ACCEPTATION = D_ACCEPTATION
FIELD_CODE_D_CLOTURE = D_CLOTURE
FIELD_CODE_D_ENVOI = D_ENVOI
FIELD_CODE_D_REPONSE = D_REPONSE
FIELD_CODE_T_REPONSE = T_REPONSE
FIELD_CODE_U_REPONSE = U_REPONSE
FIELD_CODE_C_COMPLEMENT = C_COMPLEMENT
FIELD_CODE_C_EMETTEUR = C_EMETTEUR
FIELD_CODE_C_DESTINATAIRE = C_DESTINATAIRE

STATE_CODE_A_INDEXER = A_INDEXER
STATE_CODE_A_VALIDER = A_VALIDER
STATE_CODE_REJECT = REJETE
STATE_CODE_DIFFUSE = DIFFUSE
STATE_CODE_REPONDU = REPONDU
STATE_CODE_CLOTURE = CLOTURE
STATE_CODE_VISA_INDEFINI = INDEFINI
STATE_CODE_VISA_ACCEPTE = ACCEPTE
STATE_CODE_VISA_REFUSE = REFUSE

TYPE_RESPONSE_CODE_COURRIER = COURRIER

NUM_CHRONO_UNIQUE_BY_YEAR = false
NUM_CHRONO_SEP = /
NUM_CHRONO_PATTERN = <DATE>/<SOCIETE>/<COUNTER>
NUM_CHRONO_DATE_FORMAT = yyMMdd
NUM_CHRONO_SERVICE_FORMAT = CODE
NUM_CHRONO_COUNTER_SIZE = 8

CUSTOM_PANEL_COMMENT_WIDTH=500
CUSTOM_PANEL_RESPONSE_WIDTH=800
CUSTOM_PANEL_VISA_WIDTH=800
CUSTOM_PANEL_COMMENT_HEIGHT=320
CUSTOM_PANEL_RESPONSE_HEIGHT=600
CUSTOM_PANEL_VISA_HEIGHT=620

FIELD_CODE_G_SOCIETE = G_SOCIETE