######################
# Configuration Wizard
######################
#configuration.login=Admin
#configuration.password=Admin
#configuration.xsdCheckerEnabled=true
##########
# Workflow
##########
#workflow.cacheSize=20000
#workflow.database.oracleUsed=true
#################
# Personal Space
#################
#personalSpace.clipboardSize=10
#personalSpace.historyDocumentSize=10
#personalSpace.historySearchSize=10
#personalSpace.historyAttachmentSize=10
######
# Misc
######
misc.notificationDaysNumberBeforePasswordExpiration=20
misc.deactivationSortingSearchResultNumber=5000
misc.basketShortTitleSize=50
misc.displayedBookmarksMaxNumber=500
misc.lazyModalPanelEnabled=true
# Possible values are: BLANK, FIELD_CODE and FIELD_DESCRIPTION
#misc.hierarchicalTreeNodeVariableEmptyMode=FIELD_CODE
# Defines the time interval (milliseconds) between two Poll Ajax request
#misc.applicationPollEnabled=true
#misc.applicationPollInterval=10000
# Defines the session timeout interval (milliseconds)
# 2h00
misc.sessionTimeout=7200000
# Defines the number of Tomcat sessions enabled by user : -1 defines unlimited sessions by user
#misc.numberOfSessionsByUser=-1
# Defines the document auto-lock timeout (milliseconds)
# 2h00
misc.autoLockedDocumentTimeout=7200000
# Defines if the notification messages have time out
#misc.notificationMessageTimeoutEnabled=true
# Defines the IE compatibility version
misc.compatibilityVersion.IE=11
# Defines available locale use for the application.
#misc.localeDefinition=ro;en;fr;
# Defines the number of attachments which can be added in creation pages
#document.creation.max.file.quantity=5
# If true, the message bundle key are displayed in place of translations
#misc.debugMessageBundleKey=true
######
# Pop
######
#pop.defaultCountryName=
#####
# SSO
#####
# Defines the type of SSO to use. Possible values are: SPNEGO, APACHE
#sso.type=
#########
# Display
#########
#display.attachmentLayout.defaultWidth=600
#display.attachmentLayout.defaultHeight=300
#display.attachmentLayout.defaultWidthRatio=0.4
#display.attachmentLayout.defaultHeightRatio=0.33
display.attachmentLayout.annotation.displayOwnerAndCreationDate=true
dossier.theme=AIRS_SUITE
dossier.modes=dossier

##########
# DEBUT JWS (Java Web Start)
##########
## activation globale ?
#applet.javaWebStart.activated=false
## port par d�faut de l'editDocument
#applet.javaWebStart.editDocument.serverPort=13000
## lancement automatique du module d'�dition d�s le 1er affichage de la page d'accueil ?
#applet.javaWebStart.editDocument.launchAuto=true
## port par d�faut du module de scan/ajout d'annotation
#applet.javaWebStart.imageScan.serverPort=18000
## lancement automatique du module de scan d�s le 1er affichage de la page d'accueil ?
#applet.javaWebStart.imageScan.launchAuto=true
## port par d�faut du module d'impression
#applet.javaWebStart.print.serverPort=28000
## lancement automatique d'impression d�s le 1er affichage de la page d'accueil ?
#applet.javaWebStart.print.launchAuto=false
## Autoriser l'utilisateur � d�finir ses propres r�gles JWS via l'onglet Pr�f�rences
# applet.javaWebStart.override.enabled=false
## activation du mode Citrix/TSE/Wyze (ajustement automatiquement du port des modules)
# configuration.virtualized.environment=false
# JWS et https
# nom de domaine
# applet.javaWebStart.domain=
# url/chemin vers le keystore
# applet.javaWebStart.ssl_keystore=
# password du keystore
# applet.javaWebStart.ssl_password=
# type de keystore
# applet.javaWebStart.ssl_keystore.type=
# alias de la cl� SSL
# applet.javaWebStart.ssl_key.alias=
##########
# FIN JWS
##########
#######
# Other
#######
# Enables the user role management
#user.roleEnabled=false
# Debug script: allow to compile script on runtime
script.debug=true
#attachment.applet.propertiesFilePath=C:\\AIRS_OPENFILES\\test.txt
#sign.airs.signatoryField=U_SIGNATORY
#sign.airs.signAttachmentIdField=ATTACHMENTID_TOSIGN
#sign.airs.signedAttachmentIdsField=ATTACHMENTIDS_SIGNED
#applet.nojavaclient.activated=false
#dossier.modes=dossier
#dossier.theme=AIRS_SUITE
#email.template.enabled=false
misc.notification.default.mode=top-right
misc.login.display.citation=false
misc.autoLockedDocument.automatic.unlock.leaving.viewunit=true
dossier.ws.rest.json.serialize.wrap.root.value=false
#######
# ABO_20250825
#######
email.use.replyto.property=true

sign.airs.signature.enabled=true
sign.airs.signature.auto.create.fields=true
contact.phone.numbers.available.countries=*.*