#MAIL ALERTE
MAIL_NOTIFICATION_ENABLED = true

#MODAL PANEL
CUSTOM_PANEL_COMMENT_WIDTH=500
CUSTOM_PANEL_COMMENT_HEIGHT=320

#PROFIL
PROFIL_CMPT=PF_COMPTABLE
PROFIL_ACHAT=PF_ACHAT
PROFIL_CTRLGEST=PF_CDG
PROFIL_CDP=PF_CDP
PROFIL_DAF=PF_DAF
PROFIL_DIR=PF_DIR

#FIELD
FIELD_FAC_ETAT=FACT_ETAT
FIELD_FAC_RETOUR=FACT_RETOUR
FIELD_FAC_VAL_CTRLGEST1=FACT_VAL_CTRLGEST1
FIELD_FAC_VAL_CTRLGEST2=FACT_VAL_CTRLGEST2
FIELD_FAC_VAL_CTRLGEST3=FACT_VAL_CTRLGEST3
FIELD_FAC_VAL_CDP1=FACT_VAL_CDP1
FIELD_FAC_VAL_CDP2=FACT_VAL_CDP2
FIELD_FAC_VAL_CDP3=FACT_VAL_CDP3
FIELD_FACT_USR_ACHAT=FACT_USR_ACHAT
FIELD_FACT_USR_CTRLGEST1=FACT_USR_CTRLGEST1
FIELD_FACT_USR_CTRLGEST2=FACT_USR_CTRLGEST2
FIELD_FACT_USR_CTRLGEST3=FACT_USR_CTRLGEST3
FIELD_FACT_USR_CDP1=FACT_USR_CDP1
FIELD_FACT_USR_CDP2=FACT_USR_CDP2
FIELD_FACT_USR_CDP3=FACT_USR_CDP3
FIELD_FACT_USR_DIR=FACT_USR_DIR
FIELD_FACT_CODE_CHANT1=FACT_CODE_CHANT1
FIELD_FACT_CODE_CHANT2=FACT_CODE_CHANT2
FIELD_FACT_CODE_CHANT3=FACT_CODE_CHANT3
FIELD_FACT_CHRONO=FACT_CHRONO
FIELD_FACT_DT_ACHAT=FACT_DT_ACHAT
FIELD_FACT_DT_COMPTA=FACT_DT_COMPTA
FIELD_FACT_DT_CTRLGEST=FACT_DT_CTRLGEST
FIELD_FACT_DT_CDP=FACT_DT_CDP
FIELD_FACT_CDPVALIDE=FACT_CDPVALIDE
FIELD_FACT_DT_DAF=FACT_DT_DAF
FIELD_FACT_DT_DIR=FACT_DT_DIR
FIELD_FACT_DT_PMNT=FACT_DT_PMNT
# AUTHORITY LIST VALUE
#FIELD FAC_ETAT
CODE_CMPT_TRANS=CMPT_TRANS
CODE_VALID_ACHAT=VALID_ACHAT
CODE_CMPT_VERIF=CMPT_VERIF
CODE_VALID_CTRLGEST=VALID_CTRLGEST
CODE_VALID_CDP=VALID_CDP
CODE_CMPT_PREPA_PAIE=CMPT_PREPA_PAIE
CODE_CMPT_LITIGE=CMPT_LITIGE
CODE_VALID_DAF=VALID_DAF
CODE_VALID_DIR=VALID_DIR
CODE_A_PAYER=A_PAYER
CODE_PAYEE=PAYEE
CODE_ANNULEE=ANNULE
#FIELD FAC_RETOUR
CODE_OUI=OUI
CODE_OUI_INVALIDE=OUI_INVALIDE
CODE_NON=NON
CODE_TODO=TODO
#FIELD FACT_CDPVALIDE
CODE_VALIDE=VALIDE
CODE_INVALIDE=INVALIDE


#BASE_CONNECTION
SCRIPT_DIGI=YES
#SCRIPT_DIGI=NO

ORACLE_AC_DRIVER_NAME=oracle.jdbc.driver.OracleDriver
ORACLE_AC_MAX_THREAD=20
ORACLE_AC_SEQ=com.digitech.framework.db.oracle.SequenceOraImpl
ORACLE_AC_JDBC_CONNECTION_STRING=jdbc:oracle:thin:@pc-cle3:1521:XE
ORACLE_AC_USER=AIRSFACT4_GEOCEAN
ORACLE_AC_PWD=AIRSFACT4_GEOCEAN

TIERS_DRIVER_NAME=oracle.jdbc.driver.OracleDriver
TIERS_MAX_THREAD=20
TIERS_SEQ=com.digitech.framework.db.oracle.SequenceOraImpl
TIERS_JDBC_CONNECTION_STRING=jdbc:oracle:thin:@pc-cle3:1521:XE
TIERS_USER=AIRSFACT4_GEOCEAN
TIERS_PWD=AIRSFACT4_GEOCEAN
