


!-----------------------------------------------------------------------------!
! Configure log4j's operation at the meta level                               !
!-----------------------------------------------------------------------------!
! Observe log4j parsing this file
log4j.debug=true



!-----------------------------------------------------------------------------!
! Configure categories (loggers)                                              !
!-----------------------------------------------------------------------------!

log4j.rootCategory=debug, dest3

log4j.logger.com.digitech.airsweb=error, dest1


!-----------------------------------------------------------------------------!
! Configure appenders (log destinations/targets) and their options            !
!-----------------------------------------------------------------------------!

! WRITE TO CONSOLE (stdout or stderr)
log4j.appender.dest1=org.apache.log4j.ConsoleAppender
log4j.appender.dest1.ImmediateFlush=true

! WRITE LOG TO A FILE, ROLL THE FILE AFTER SOME SIZE
log4j.appender.dest3=org.apache.log4j.RollingFileAppender

log4j.appender.dest3.File=${dossier_app}/logs/dossiers_webapp.log
log4j.appender.dest3.MaxFileSize=10000KB
log4j.appender.dest3.MaxBackupIndex=2


!-----------------------------------------------------------------------------!
! Configure appender layouts (log formats) and their options                  !
!-----------------------------------------------------------------------------!


log4j.appender.dest1.layout=org.apache.log4j.SimpleLayout


log4j.appender.dest3.layout=org.apache.log4j.PatternLayout
log4j.appender.dest3.layout.ConversionPattern=[%d{ISO8601}]%5p%6.6r[%t]%x(%F:%L) - %m%n