[[document_rest]]
=== Document

==== Client

La classe `com.digitech.dossier.rest.ws.impl.DocumentClient` de la librairie *com.digitech.airs:dossier-rest-client:{dossier-rest-client-version}* abstrait
l'utilisation de cette *API*.

Voir <<appendix_document_client_samples, exemples ici>>.

==== Méthodes
===== {POST} /document

Cette méthode permet de créer un document

[cols="1a,1a,2a,1a,4a",options="header"]
.Paramètres en entrée
|===
|Paramètre|Type|Description|Requis|Exemple
|*documentData*|{multipart}|Ensemble de données du document|[red]*Oui*|
[source,json]
----
{
  "contentType": "CR",
  "secretLevel": 0,
  "fields": [{
    "code": "CR",
    "field": "Title"}],
  "data": ["CR"],
  "filename": "test",
  "flowCode": "CR",
  "scriptCode": "test"
}
----
|*fileData*|{multipart}|Liste de fichiers|[green]*Non*|
|===
cf le chapitre <<appendix_document>> pour une description de la structure documentData (Se réferer à WSCommonDocumentType).

[NOTE]
====
Le type de contenu du corps de la requête doit être "multipart/form-data".
Pour ajouter plusieurs fichiers au document, il suffit d'envoyer plusieurs fois le paramètre fileData dans le corps de la requête.
====
[source]
.appel _curl_
----
curl --location --request POST '<host>:<port>/<context>/rest/document' \
--header 'Authorization: Basic <credencials>'  \
--form 'documentData="{
    \"contentType\": \"CR\",
    \"fields\": [
      {
        \"code\": \"D_MODIF\",
        \"field\": \"04/02/2021 16:58:35\"
      },
      {
        \"code\": \"CR_DES\",
        \"field\": \"Test DOC\"
      },
      {
        \"code\": \"CR_REDACTEUR\",
        \"field\": \"1\"
      },
      {
        \"code\": \"CR_DATE\",
        \"field\": \"01/01/2022 0:00:00\"
      },
      {
        \"code\": \"CR_RESUME\",
        \"field\": \"TEST DOC\"
      }
    ]
  }";type=application/json' \
--form 'fileData=@"/C:/TEST1.pdf"' \
--form 'fileData=@"/C:/TEST2.pdf"'
----

[cols="^1a,4a",options="header"]
.Réponses
|===
|Code Http|Description
|[lime]*200*|Opération réussie (cf. <<document_rest_response>>)
|[red]*401*|Authentification non fournie
|[red]*500*|Erreur interne au serveur/service
|===

[[document_rest_response]]
[source,text]
.Retour, Identifiant du document
----
6733
----

===== {GET} /document/{docId}

Cette méthode permet de récupérer les métadonnées d'un document à partir de son identifiant

[cols="1a,1a,4a,1a,2a",options="header"]
.Paramètres en entrée
|===
|Paramètre|Type|Description|Requis|Exemple
|*docId*|{path}|Identifiant du document|[red]*Oui*|
4959
|===

[source]
.appel _curl_
----
curl -X 'GET' \
  '<host>:<port>/<context>/rest/document/4959' \
  -H 'accept: application/json' \
  -H 'Authorization: Basic <credencials>'
----

[cols="^1a,4a",options="header"]
.Réponses
|===
|Code Http|Description
|[lime]*200*|Opération réussie (cf. <<documentgetjson_response>>)
|[red]*401*|Authentification non fournie
|[red]*404*|Document non trouvé
|[red]*500*|Erreur interne au serveur/service
|===

[[documentgetjson_response]]
[source,json]
.Structure de retour
----
{
  "WSDocumentType": {
    "contentType": "CR",
    "secretLevel": 10,
    "filename": "1.doc",
    "data":"<base64>",
    "fields": [
      {
        "code": "D_MODIF",
        "field": "12/07/2022 15:32:47"
      },
      {
        "code": "CR_THEME",
        "field": "Réunion Transverse"
      },
      {
        "code": "D_CREAT",
        "field": "24/08/2021 11:02:30"
      },
      {
        "code": "CR_DES",
        "field": "test html"
      },
      {
        "code": "CR_REDACTEUR",
        "field": "ADM Dossier"
      },
      {
        "code": "CR_DATE",
        "field": "24/08/2021 0:00:00"
      },
      {
        "code": "CR_RESUME",
        "field": "test html"
      }
    ]
  }
}
----

cf le chapitre <<appendix_document>> pour une description de la structure de retour.

===== {GET} /document/{docId}/history

Cette méthode permet de récupérer l'historique (liste des événements) d'un document à partir de son identifiant. Les événements sont retournés du plus récent au plus ancien.

[cols="1a,1a,4a,1a,2a",options="header"]
.Paramètres en entrée
|===
|Paramètre|Type|Description|Requis|Exemple
|*docId*|{path}|Identifiant du document|[red]*Oui*|4959
|*filter*|{query}|Filtre des événements à remonter (valeur par défaut *NONE*) +
 +
 *NONE* : événements du document + événements de dossier externe (signature) +
 *DOCUMENT* : événements du document uniquement +
 *DOSSIER_EXTERNE* : événements de dossier externe (signature) uniquement|[green]*Non*|DOCUMENT
|===

[source]
.appel _curl_
----
curl -X 'GET' \
  '<host>:<port>/<context>/rest/document/4959/history?filter=NONE' \
  -H 'accept: application/json' \
  -H 'Authorization: Basic <credencials>'
----

[cols="^1a,4a",options="header"]
.Réponses
|===
|Code Http|Description
|[lime]*200*|Opération réussie (cf. <<documenthistoryjson_response>>)
|[red]*401*|Authentification non fournie
|[red]*404*|Document non trouvé
|[red]*500*|Erreur interne au serveur/service
|===

[[documenthistoryjson_response]]
[source,json]
.Structure de retour
----
[
  {
    "id": 12045,
    "date": "12/07/2022 15:32:47",
    "type": 2,
    "typeCode": "MODIFICATION",
    "comment": "Mise à jour des métadonnées",
    "actorId": 1,
    "actorName": "ADM Dossier",
    "dossierExterne": false
  },
  {
    "id": 11873,
    "date": "24/08/2021 11:02:30",
    "type": 1,
    "typeCode": "CREATION",
    "actorId": 1,
    "actorName": "ADM Dossier",
    "dossierExterne": false
  }
]
----

[cols="2a,3a,1a",options="header"]
.Description d'un événement (WSHistoryEventType)
|===
|Champ|Description|Type
|*id*|Identifiant de l'événement|_integer_
|*date*|Date de l'événement|_string_
|*type*|Identifiant numérique du type d'événement|_integer_
|*typeCode*|Code (clé textuelle) du type d'événement|_string_
|*comment*|Commentaire associé à l'événement|_string_
|*actorId*|Identifiant de l'utilisateur à l'origine de l'événement|_integer_
|*actorName*|Nom de l'utilisateur à l'origine de l'événement|_string_
|*dossierExterne*|`true` si l'événement provient d'un dossier externe (signature)|_boolean_
|===

===== {PATCH} /document/{docId}

Cette méthode permet de mettre à jour les métadonnées d'un document

[cols="1a,1a,2a,1a,4a",options="header"]
.Paramètres en entrée
|===
|Paramètre|Type|Description|Requis|Exemple
|*docId*|{path}|Identifiant du document|[red]*Oui*|4959
|*documentData*|{multipart}|Ensemble de données du document|[red]*Oui*|
[source,json]
----
{
  "contentType": "CR",
  "secretLevel": 0,"fields": [{
    "code": "CR",
    "field": "Title"}],
  "data": ["CR"],
  "filename": "test",
  "flowCode": "CR",
  "scriptCode": "test"
}
----
|*fileData*|{multipart}|Liste de fichiers|[green]*Non*|
|===
cf le chapitre <<appendix_document>> pour une description de la structure documentData.
[NOTE]
====
Le type de contenu du corps de la requête doit être "multipart/form-data".
Pour ajouter plusieurs fichiers au document, il suffit d'envoyer plusieurs fois le paramètre fileData dans le corps de la requête.
====
[source]
.appel _curl_
----
curl -X 'PATCH' \
  '<host>:<port>/<context>/rest/document/4959' \
  -H 'accept: text/plain' \
  -H 'Content-Type: application/json' \
  -d '{
    "fields": [
      {
        "code": "CR_DES",
        "field": "test html"
      },
      {
        "code": "CR_RESUME",
        "field": "test html"
      }
    ]
  }'
----

[cols="^1a,4a",options="header"]
.Réponses
|===
|Code Http|Description
|[lime]*200*|Opération réussie (cf. <<documentupdatejson_response>>)
|[red]*401*|Authentification non fournie
|[red]*404*|Document non trouvé
|[red]*500*|Erreur interne au serveur/service
|===

[[documentupdatejson_response]]
[source,text]
.Exemple de retour
----
4959
----

===== {DELETE} /document/{docId}

Cette méthode permet de supprimer logiquement un document.
[NOTE]
====
Les documents enfants seront aussi supprimés.
====
[cols="1a,1a,4a,1a,2a",options="header"]
.Paramètres en entrée
|===
|Paramètre|Type|Description|Requis|Exemple
|*docId*|{path}|Identifiant du document|[red]*Oui*|4959

|===

[source]
.appel _curl_
----
curl -X 'DELETE' \
  '<host>:<port>/<context>/rest/document/4959' \
  -H 'accept: text/plain' \
  -H 'Authorization: Basic <credencials>'
----

[cols="^1a,4a",options="header"]
.Réponses
|===
|Code Http|Description
|[lime]*200*|Opération réussie (cf. <<documentdeletejson_response>>)
|[red]*401*|Authentification non fournie
|[red]*404*|Document non trouvé
|[red]*500*|Erreur interne au serveur/service
|===

[[documentdeletejson_response]]
[source,text]
.Liste d'identifiants des documents supprimés
----
[4959, 2845]
----

===== {DELETE} /document/remove/{docId}

Cette méthode permet de supprimer physiquement un document.
[NOTE]
====
Les documents enfants seront aussi supprimés.

====
[cols="1a,1a,4a,1a,2a",options="header"]
.Paramètres en entrée
|===
|Paramètre|Type|Description|Requis|Exemple
|*docId*|{path}|Identifiant du document|[red]*Oui*|4959
|===

[source]
.appel _curl_
----
curl -X 'DELETE' \
  '<host>:<port>/<context>/rest/document/remove/4959' \
  -H 'accept: text/plain' \
  -H 'Authorization: Basic <credencials>'
----

[cols="^1a,4a",options="header"]
.Réponses
|===
|Code Http|Description
|[lime]*200*|Opération réussie (cf. <<documentremovejson_response>>)
|[red]*401*|Authentification non fournie
|[red]*404*|Document non trouvé
|[red]*500*|Erreur interne au serveur/service
|===

[[documentremovejson_response]]
[source,text]
.Liste d'identifiants des documents supprimés
----
[4959, 2845]
----

===== {PATCH} /document/unlock/{docId}

Cette méthode permet de supprimer le verrou attaché à un document.

[IMPORTANT]
====
L'utilisateur connecté doit posséder le droit *DOSSIER_ADM_AIRS_ADMIN*.
====

[cols="1a,1a,4a,1a,2a",options="header"]
.Paramètres en entrée
|===
|Paramètre|Type|Description|Requis|Exemple
|*docId*|{path}|Identifiant du document|[red]*Oui*|4959
|===

[source]
.appel _curl_
----
curl -X 'DELETE' \
  '<host>:<port>/<context>/rest/document/unlock/4959' \
  -H 'accept: text/plain' \
  -H 'Authorization: Basic <credencials>'
----

[cols="^1a,4a",options="header"]
.Réponses
|===
|Code Http|Description
|[lime]*200*, [lime]*204*|Opération réussie
|[red]*401*|Authentification non fournie
|[red]*404*|Document non trouvé
|[red]*500*|Erreur interne au serveur/service
|===

===== {PATCH} /document/unlockAll

Cette méthode permet de supprimer tous les verrous en cours sur des documents

[IMPORTANT]
====
L'utilisateur connecté doit posséder le droit *DOSSIER_ADM_AIRS_ADMIN*.
====

[cols="1a,1a,4a,1a,2a",options="header"]
.Paramètres en entrée
|===
|Paramètre|Type|Description|Requis|Exemple
|===

[source]
.appel _curl_
----
curl -X 'DELETE' \
  '<host>:<port>/<context>/rest/document/unlockAll' \
  -H 'accept: text/plain' \
  -H 'Authorization: Basic <credencials>'
----

[cols="^1a,4a",options="header"]
.Réponses
|===
|Code Http|Description
|[lime]*200*, [lime]*204*|Opération réussie (cf. <<documentunlockalljson_response>>)
|[red]*401*|Authentification non fournie
|[red]*404*|Document non trouvé
|[red]*500*|Erreur interne au serveur/service
|===

[[documentunlockalljson_response]]
[source,text]
.Liste d'identifiants des documents pour lequel un verrou a été supprimé
----
[4959, 2845]
----

===== {PATCH} /document/lock/{docId}

Cette méthode permet d'ajouter un verrou à un document.

[IMPORTANT]
====
L'utilisateur connecté doit posséder le droit *DOSSIER_ADM_AIRS_ADMIN*.
====

[NOTE]
====
Le verrou sera associé à l'utilisateur appelant, contrairement au _endpoint_ défini dans le prochain chapitre
====

[cols="1a,1a,4a,1a,2a",options="header"]
.Paramètres en entrée
|===
|Paramètre|Type|Description|Requis|Exemple
|*docId*|{path}|Identifiant du document|[red]*Oui*|4959
|===

[source]
.appel _curl_
----
curl -X 'DELETE' \
  '<host>:<port>/<context>/rest/document/lock/4959' \
  -H 'accept: text/plain' \
  -H 'Authorization: Basic <credencials>'
----

[cols="^1a,4a",options="header"]
.Réponses
|===
|Code Http|Description
|[lime]*200*, [lime]*204*|Opération réussie
|[red]*401*|Authentification non fournie
|[red]*404*|Document non trouvé
|[red]*409*|Document déjà verrouillé
|[red]*500*|Erreur interne au serveur/service
|===

===== {PATCH} /document/lock/{docId}/{userId}

Cette méthode permet d'ajouter un verrou à un document, pour un utilisateur particulier

[IMPORTANT]
====
L'utilisateur connecté doit posséder le droit *DOSSIER_ADM_AIRS_ADMIN*.
====

[cols="1a,1a,4a,1a,2a",options="header"]
.Paramètres en entrée
|===
|Paramètre|Type|Description|Requis|Exemple
|*docId*|{path}|Identifiant du document|[red]*Oui*|4959
|*userId*|{path}|Identifiant de l'utilisateur pour lequel le verrou est souhaité|[red]*Oui*|12
|===

[source]
.appel _curl_
----
curl -X 'DELETE' \
  '<host>:<port>/<context>/rest/document/lock/4959/12' \
  -H 'accept: text/plain' \
  -H 'Authorization: Basic <credencials>'
----

[cols="^1a,4a",options="header"]
.Réponses
|===
|Code Http|Description
|[lime]*200*, [lime]*204*|Opération réussie
|[red]*401*|Authentification non fournie
|[red]*404*|Document non trouvé
|[red]*409*|Document déjà verrouillé
|[red]*500*|Erreur interne au serveur/service
|===

===== {GET} /document/{docId}/comments

Cette méthode permet de récupérer la liste des commentaires d'un document visibles par l'utilisateur connecté.

[IMPORTANT]
====
L'utilisateur connecté doit posséder le droit *DOSSIERS_TAB_COMMENTAIRE_READ*.
====

[cols="1a,1a,4a,1a,2a",options="header"]
.Paramètres en entrée
|===
|Paramètre|Type|Description|Requis|Exemple
|*docId*|{path}|Identifiant du document|[red]*Oui*|4959
|===

[source]
.appel _curl_
----
curl -X 'GET' \
  '<host>:<port>/<context>/rest/document/4959/comments' \
  -H 'accept: application/json' \
  -H 'Authorization: Basic <credencials>'
----

[cols="^1a,4a",options="header"]
.Réponses
|===
|Code Http|Description
|[lime]*200*|Opération réussie (cf. <<documentcommentsjson_response>>)
|[red]*401*|Authentification non fournie
|[red]*404*|Document non trouvé
|[red]*500*|Erreur interne au serveur/service
|===

[[documentcommentsjson_response]]
[source,json]
.Structure de retour
----
[
  {
    "id": 42,
    "date": "29/05/2026 15:32:47",
    "comment": "Commentaire de test",
    "actorId": 1,
    "actorName": "ADM Dossier",
    "public": true
  }
]
----

[cols="2a,3a,1a",options="header"]
.Description d'un commentaire (WSCommentType)
|===
|Champ|Description|Type
|*id*|Identifiant du commentaire|_integer_
|*date*|Date du commentaire|_string_
|*comment*|Texte du commentaire|_string_
|*actorId*|Identifiant de l'utilisateur auteur du commentaire|_integer_
|*actorName*|Nom de l'utilisateur auteur du commentaire|_string_
|*public*|`true` si le commentaire est public (visible par tous), `false` s'il est privé/partagé|_boolean_
|===

===== {POST} /document/{docId}/comments

Cette méthode permet d'ajouter un commentaire à un document.

[IMPORTANT]
====
L'utilisateur connecté doit posséder le droit *DOSSIERS_TAB_COMMENTAIRE_WRITE*.
====

[NOTE]
====
Seuls les champs *comment* et *public* du corps de la requête sont pris en compte ; les autres champs (`id`, `date`, `actorId`, `actorName`) sont calculés par le serveur. Le texte du commentaire (*comment*) est obligatoire.
====

[cols="1a,1a,2a,1a,4a",options="header"]
.Paramètres en entrée
|===
|Paramètre|Type|Description|Requis|Exemple
|*docId*|{path}|Identifiant du document|[red]*Oui*|4959
|*delegated*|{query}|Login d'un utilisateur délégué. Si renseigné, le commentaire est créé au nom de cet utilisateur.|[green]*Non*|jdupont
|*comment*|{body}|Données du commentaire (Json)|[red]*Oui*|
[source,json]
----
{
  "comment": "Commentaire de test",
  "public": true
}
----
|===

[source]
.appel _curl_
----
curl -X 'POST' \
  '<host>:<port>/<context>/rest/document/4959/comments' \
  -H 'accept: text/plain' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Basic <credencials>' \
  -d '{
    "comment": "Commentaire de test",
    "public": true
  }'
----

[cols="^1a,4a",options="header"]
.Réponses
|===
|Code Http|Description
|[lime]*200*|Opération réussie (cf. <<documentaddcommentjson_response>>)
|[red]*400*|Texte du commentaire manquant
|[red]*401*|Authentification non fournie
|[red]*404*|Document non trouvé
|[red]*500*|Erreur interne au serveur/service
|===

[[documentaddcommentjson_response]]
[source,text]
.Retour, identifiant du commentaire créé
----
42
----

===== {PATCH} /document/{docId}/comments/{commentId}

Cette méthode permet de mettre à jour un commentaire d'un document.

[IMPORTANT]
====
L'utilisateur connecté doit être l'auteur du commentaire, ou posséder le droit *DOSSIERS_MODIFY_COMMENT_ALL*.
====

[NOTE]
====
Seuls les champs *comment* et *public* du corps de la requête sont pris en compte. Le texte du commentaire (*comment*) est obligatoire.
====

[cols="1a,1a,2a,1a,4a",options="header"]
.Paramètres en entrée
|===
|Paramètre|Type|Description|Requis|Exemple
|*docId*|{path}|Identifiant du document|[red]*Oui*|4959
|*commentId*|{path}|Identifiant du commentaire|[red]*Oui*|42
|*delegated*|{query}|Login d'un utilisateur délégué. Si renseigné, l'opération est réalisée au nom de cet utilisateur.|[green]*Non*|jdupont
|*comment*|{body}|Données du commentaire (Json)|[red]*Oui*|
[source,json]
----
{
  "comment": "Commentaire mis à jour",
  "public": false
}
----
|===

[source]
.appel _curl_
----
curl -X 'PATCH' \
  '<host>:<port>/<context>/rest/document/4959/comments/42' \
  -H 'accept: text/plain' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Basic <credencials>' \
  -d '{
    "comment": "Commentaire mis à jour",
    "public": false
  }'
----

[cols="^1a,4a",options="header"]
.Réponses
|===
|Code Http|Description
|[lime]*200*|Opération réussie (cf. <<documentupdatecommentjson_response>>)
|[red]*400*|Texte du commentaire manquant
|[red]*401*|Authentification non fournie
|[red]*404*|Document ou commentaire non trouvé
|[red]*500*|Erreur interne au serveur/service
|===

[[documentupdatecommentjson_response]]
[source,text]
.Retour, identifiant du commentaire mis à jour
----
42
----

===== {DELETE} /document/{docId}/comments/{commentId}

Cette méthode permet de supprimer un commentaire d'un document.

[IMPORTANT]
====
L'utilisateur connecté doit être l'auteur du commentaire, ou posséder le droit *ADMINISTRER*.
====

[cols="1a,1a,2a,1a,4a",options="header"]
.Paramètres en entrée
|===
|Paramètre|Type|Description|Requis|Exemple
|*docId*|{path}|Identifiant du document|[red]*Oui*|4959
|*commentId*|{path}|Identifiant du commentaire|[red]*Oui*|42
|*delegated*|{query}|Login d'un utilisateur délégué. Si renseigné, l'opération est réalisée au nom de cet utilisateur.|[green]*Non*|jdupont
|===

[source]
.appel _curl_
----
curl -X 'DELETE' \
  '<host>:<port>/<context>/rest/document/4959/comments/42' \
  -H 'accept: application/json' \
  -H 'Authorization: Basic <credencials>'
----

[cols="^1a,4a",options="header"]
.Réponses
|===
|Code Http|Description
|[lime]*200*|Opération réussie (cf. <<documentdeletecommentjson_response>>)
|[red]*401*|Authentification non fournie
|[red]*404*|Document ou commentaire non trouvé
|[red]*500*|Erreur interne au serveur/service
|===

[[documentdeletecommentjson_response]]
[source,text]
.Retour, identifiant du commentaire supprimé
----
42
----