[[search_rest]]
=== Search

[NOTE]
====
Ce {webservice} n'est disponible qu'à partir de la version *8* de {arcadeged}
====

==== Client

La classe `com.digitech.dossier.rest.ws.ISearchClient` de la librairie *com.digitech.airs:dossier-rest-client:{dossier-rest-client-version}* abstrait
l'utilisation
de cette *API*.

==== Méthodes
===== {GET} /search/docCount

Cette méthode renvoie le nombre de documents remontés par la requête AIRS

[cols="1a,1a,4a,2a,3a",options="header"]
.Paramètres en entrée
|===
|Paramètre|Type|Description|Requis|Exemple
|*airsRequest*|{query}|Requête AIRS|[red]*Oui*|D_CREAT>01/01/2018
|*ctyCodes*|{query}|Liste des types de contenu dans lesquels la recherche est exécutée
[TIP]
====
Pour effectuer une recherche sur tous les types de contnues, vous pouvez spécifier \*.* . +
La recherche sera alors jouée sur tous les types de contenu ou ceux appartenant au *flowCode*
====
|[red]*Oui*|CR
|*flowCode*|{query}|Code du flux dans lequel la recherche est effectué|[green]*Non*|CR
|*sort*|{query}|Critères de tri, défini par le *<code du champ>[,<direction>]*
[TIP]
====
Si vous souhaitez cumuler les champs de tri, veuillez simplement répéter l'attribut, ex.
[source,text]
----
sort=D_CREAT,desc&sort=RESUME,asc&sort=TITRE
----
====
|[green]*Non*|*D_CREAT,desc*
|*delegated*|{query}|*login* de l'utilisateur pour lequel la recherche sera réellement jouée (déléguée).
[CAUTION]
====
L'utilisateur *[underline]#authentifié#* doit posséder le droit *DOSSIERS_DELEGATE_SEARCH_APIS* pour pouvoir effectuer une recherche _"déléguée"_.
====
|[green]*Non*|_n.felix_
|===

[source]
.appel _curl_
----
curl -X 'GET' \
  'http[s]://<host>:<port>/<context>/rest/search/docCount?airsRequest=D_CREAT%3E01%2F01%2F2018&ctyCodes=CR&flowCode=CR' \
  -H 'accept: application/json' \
  -H 'Authorization: Basic <credencials>'
----

[cols="^1a,4a",options="header"]
.Réponses
|===
|Code Http|Description
|[lime]*200*|Opération réussie (cf. <<search_getdocCountjson_response>>)
|[red]*401*|Authentification non fournie
|[red]*500*|Erreur interne au serveur/service
|===

[[search_getdocCountjson_response]]
[source,text]
.Integer
----
34
----

===== {GET} /search/docLink

Cette méthode permet d'obtenir les liens URL vers les documents renvoyés par la requête AIRS.

[cols="1a,1a,4a,2a,3a",options="header"]
.Paramètres en entrée
|===
|Paramètre|Type|Description|Requis|Exemple
|*airsRequest*|{query}|Requête AIRS|[red]*Oui*|D_CREAT>01/01/2018
|*ctyCodes*|{query}|Liste des types de contenu dans lesquels la recherche est exécutée.
[TIP]
====
Pour effectuer une recherche sur tous les types de contnues, vous pouvez spécifier \*.* . +
La recherche sera alors jouée sur tous les types de contenu ou ceux appartenant au *flowCode*
====
|[red]*Oui*|CR
|*flowCode*|{query}|Code du flux dans lequel la recherche est effectué|[green]*Non*|CR
|*sort*|{query}|Critères de tri, défini par le *<code du champ>[,<direction>]*
[TIP]
====
Si vous souhaitez cumuler les champs de tri, veuillez simplement répéter l'attribut, ex.
[source,text]
----
sort=D_CREAT,desc&sort=RESUME,asc&sort=TITRE
----
====
|[green]*Non*|*D_CREAT,desc*
|*delegated*|{query}|*login* de l'utilisateur pour lequel la recherche sera réellement jouée (déléguée).
[CAUTION]
====
L'utilisateur *[underline]#authentifié#* doit posséder le droit *DOSSIERS_DELEGATE_SEARCH_APIS* pour pouvoir effectuer une recherche _"déléguée"_.
====
|[green]*Non*|_n.felix_
|===

[source]
.appel _curl_
----
curl -X 'GET' \
  'http[s]://<host>:<port>/<context>/rest/search/docLink?airsRequest=D_CREAT%3E01%2F01%2F2018&ctyCodes=CR&flowCode=CR' \
  -H 'accept: application/json' \
  -H 'Authorization: Basic <credencials>'
----

[cols="^1a,4a",options="header"]
.Réponses
|===
|Code Http|Description
^|[lime]*200*|Opération réussie (cf. <<search_getdocLinkjson_response>>)
^|[red]*401*|Authentification non fournie
^|[red]*500*|Erreur interne au serveur/service
|===

[[search_getdocLinkjson_response]]
[source,json]
.Structure de retour
----
[
  "faces/redirect.jsp?authentication=HPa4o3rdP3jo%2FTvySbkDVZMK%2FYuCpRx%2BjOSv5Tp0t9z%2BdIpmSlbBGpgF4ZT9SjaaM5yiNjYtgZ4kuNmMit%2F2LyaaTta6zfYjRsEnfVqCIaXfQqrdxfjVXQNcpILl0f2I1L%2F%2Bovj2AsDD9r3x127k36wMF8MTOW3K8NMG5ouxH8k%3D&outcome=gotoDocumentUnitaire&docId=6868&flowCode=CR",
  "faces/redirect.jsp?authentication=qJoexW7AAhobyxEaEGCpYq77hjkdaayibx%2B5CiCHmX3JD5PbX%2FNtkSQG%2B38CNrNezmUjKGQc7uBjazIzQZwMAeQcgv7dhrpeJH64jAtkBbM37j279eWg2lcQltrqWGF2wqPXrsIejkUGwMqa4S3AQR1CSGHitW9owSwqmuFWXwM%3D&outcome=gotoDocumentUnitaire&docId=6867&flowCode=CR"
]
----

[IMPORTANT]
====
Les URL doivent être ajoutés à l'adresse http[s]://<host>:<port>/<context>/ pour pouvoir être utilisées.
====

[[rest_search_results]]
===== {GET} /search/results

Cette méthode permet d'obtenir les métadonnées des documents renvoyés par la requête AIRS.

[cols="1a,1a,4a,2a,3a",options="header"]
.Paramètres en entrée
|===
|Paramètre|Type|Description|Requis|Exemple
|*airsRequest*|{query}|Requête AIRS|[red]*Oui*|D_CREAT>01/01/2018
|*ctyCodes*|{query}|Liste des types de contenu dans lesquels la recherche est exécutée
[TIP]
====
Pour effectuer une recherche sur tous les types de contnues, vous pouvez spécifier \*.* . +
La recherche sera alors jouée sur tous les types de contenu ou ceux appartenant au *flowCode*
====
|[red]*Oui*|CR
|*flowCode*|{query}|Code du flux dans lequel la recherche est effectué|[green]*Non*|CR
|*sort*|{query}|Critères de tri, défini par le *<code du champ>[,<direction>]*
[TIP]
====
Si vous souhaitez cumuler les champs de tri, veuillez simplement répéter l'attribut, ex.
[source,text]
----
sort=D_CREAT,desc&sort=RESUME,asc&sort=TITRE
----
====
|[green]*Non*|*D_CREAT,desc*
|*delegated*|{query}|*login* de l'utilisateur pour lequel la recherche sera réellement jouée (déléguée).
[CAUTION]
====
L'utilisateur *[underline]#authentifié#* doit posséder le droit *DOSSIERS_DELEGATE_SEARCH_APIS* pour pouvoir effectuer une recherche _"déléguée"_.
====
|[green]*Non*|_n.felix_
|===

[source]
.appel _curl_
----
curl -X 'GET' \
  'http[s]://<host>:<port>/<context>/rest/search/results?airsRequest=D_CREAT%3E01%2F01%2F2018&ctyCodes=CR&flowCode=CR' \
  -H 'accept: application/json' \
  -H 'Authorization: Basic <credencials>'
----

[cols="^1a,4a",options="header"]
.Réponses
|===
|Code Http|Description
^|[lime]*200*|Opération réussie (cf. <<search_getresultsjson_response>>)
^|[red]*401*|Authentification non fournie
^|[red]*500*|Erreur interne au serveur/service
|===

[[search_getresultsjson_response]]
[source,json]
.WSSearchResultType
----
[
  {
    "refAirsId": 4372,
    "fields": [
      {
        "code": "D_MODIF",
        "field": "04/02/2021 17:04:36"
      },
      {
        "code": "CR_THEME",
        "field": "172"
      },
      {
        "code": "D_CREAT",
        "field": "13/01/2020 16:51:20"
      },
      {
        "code": "CR_DES",
        "field": "CR réu. transverse du lundi 13 janvier 2020-1"
      },
      {
        "code": "CR_REDACTEUR",
        "field": "7"
      },
      {
        "code": "CR_DATE",
        "field": "01/01/2022 0:00:00"
      },
      {
        "code": "CR_RESUME",
        "field": "CR réu. transverse du lundi 13 janvier 2020"
      },
      {
        "code": "T_PRIOR",
        "field": ""
      },
      {
        "code": "MULTI",
        "field": ""
      },
      {
        "code": "CORRES",
        "field": ""
      },
      {
        "code": "MASQUE_NUM",
        "field": ""
      }
    ]
  },
  {
    "refAirsId": 4473,
    "fields": [
      {
        "code": "D_MODIF",
        "field": "31/01/2020 14:20:19"
      },
      {
        "code": "CR_THEME",
        "field": "174"
      },
      {
        "code": "D_CREAT",
        "field": "31/01/2020 14:20:19"
      },
      {
        "code": "CR_DES",
        "field": "Café Sideral 3"
      },
      {
        "code": "CR_REDACTEUR",
        "field": "11"
      },
      {
        "code": "CR_DATE",
        "field": "31/01/2020 0:00:00"
      },
      {
        "code": "CR_RESUME",
        "field": "Compte rendu du 3ème café SIDERAL"
      },
      {
        "code": "T_PRIOR",
        "field": ""
      },
      {
        "code": "MULTI",
        "field": ""
      },
      {
        "code": "CORRES",
        "field": ""
      },
      {
        "code": "MASQUE_NUM",
        "field": ""
      }
    ]
  }
]
----
cf le chapitre <<appendix_search_results_v1>> pour une description de la structure de retour.

[[rest_search_results_v2]]
===== {GET} /search/v2/results

Tout comme l'API décrite dans le chapitre précédent (<<rest_search_results>>), cette méthode permet d'obtenir les métadonnées des documents renvoyés par
la requête AIRS, +
[underline]#mais# les résultats sont désormais paginées.

Ceci permet alors à l'appelant de gérer comme il le souhaite le nombre de résultats à récupérer, comme naviguer parmi ces résultats, ...

[cols="1a,1a,4a,2a,3a",options="header"]
.Paramètres en entrée
|===
|Paramètre|Type|Description|Requis|Exemple
|*airsRequest*|{query}|Requête AIRS|[red]*Oui*|D_CREAT>01/01/2018
|*ctyCodes*|{query}|Liste des types de contenu dans lesquels la recherche est exécutée
[TIP]
====
Pour effectuer une recherche sur tous les types de contnues, vous pouvez spécifier \*.* . +
La recherche sera alors jouée sur tous les types de contenu ou ceux appartenant au *flowCode*
====
|[red]*Oui*|CR
|*flowCode*|{query}|Code du flux dans lequel la recherche est effectué|[green]*Non*|CR
|*page*|{query}|Numéro de page souhaitée (voir la |[green]*Non*, défaut : *0*|
|*size*|{query}|nombre de résultats maximum renvoyés|[green]*Non*, défaut : *20*|
|*sort*|{query}|Critères de tri, défini par le *<code du champ>[,<direction>]*
[TIP]
====
Si vous souhaitez cumuler les champs de tri, veuillez simplement répéter l'attribut, ex.
[source,text]
----
sort=D_CREAT,desc&sort=RESUME,asc&sort=TITRE
----
====
|[green]*Non*|*D_CREAT,desc*
|*delegated*|{query}|*login* de l'utilisateur pour lequel la recherche sera réellement jouée (déléguée).
[CAUTION]
====
L'utilisateur *[underline]#authentifié#* doit posséder le droit *DOSSIERS_DELEGATE_SEARCH_APIS* pour pouvoir effectuer une recherche _"déléguée"_.
====
|[green]*Non*|_n.felix_
|===

[source]
.appel _curl_
----
curl -X 'GET' \
  'http[s]://<host>:<port>/<context>/rest/search/v2/results?airsRequest=D_CREAT%3C24%2F12%2F2024&ctyCodes=%2A.%2A&page=1&size=50' \
  -H 'accept: application/json' \
  -H 'Authorization: Basic <credencials>'
----

[cols="^1a,4a",options="header"]
.Réponses
|===
|Code Http|Description
^|[lime]*200*|Opération réussie (cf. <<search_getresultsjson_response_v2>>)
^|[red]*401*|Authentification non fournie
^|[red]*500*|Erreur interne au serveur/service
|===

[[search_getresultsjson_response_v2]]
[source,json]
.PageableSearchResults
----
{
  "documents": [
    {
      "id": 1040,
      "ctCode": "PRO_CLIENT",
      "fields": [
        {
          "code": "PRO_DETAILS",
          "field": ""
        },
        {
          "code": "D_MODIF",
          "field": "14/11/2018 11:16:07"
        },
        {
          "code": "PRO_CLI_SATISF",
          "field": ""
        },
        {
          "code": "PRO_CLI_CONTACT10",
          "field": ""
        },
        {
          "code": "PRO_CLI_INES",
          "field": "Non défini"
        },
        {
          "code": "PRO_CLI_CONTACT9",
          "field": ""
        },
        {
          "code": "PRO_CLI_CONTACT8",
          "field": ""
        },
        {
          "code": "PRO_CLI_CONTACT7",
          "field": ""
        },
        {
          "code": "D_CREAT",
          "field": "25/04/2017 17:02:43"
        },
        {
          "code": "PRO_CLI_ENT",
          "field": "153"
        }
      ]
    },
    {
      "id": 1153,
      "ctCode": "PRO_AFFAIRE",
      "fields": [
        {
          "code": "PRO_AFF_TYPE",
          "field": "7"
        },
        {
          "code": "PRO_DETAILS",
          "field": "Commande via UGAP des licences : Délib + eDélib + Webdélib + Mobilité sous Windows (pour remplacer Qualigraf, notez que cette partie a été mise à part avec un délai de livraison fixé au 28/02/2018 afin de nous laisser le temps de développer l'outil attendu pour fin d'année, cela permettra de ne pas bloquer la facturation sur le reste). \nLa commande SCC inclut également les prestations permettant d'initialiser le projet et de facturer : RLC, etude et cr + installation pour 7 K€\n\nLe client est en train de préparer un marché négocié en direct avec nous pour le reste des prestations"
        },
        {
          "code": "D_MODIF",
          "field": "15/06/2017 11:11:38"
        },
        {
          "code": "PRO_APP_MEP_SRV_HEBERG",
          "field": ""
        },
        {
          "code": "PRO_AFF_COM_NUM",
          "field": ""
        },
        {
          "code": "PRO_AFF_NOM",
          "field": "Délib"
        }
      ]
    }
  ],
  "page": {
    "size": 50,
    "number": 1,
    "totalResults": 3544,
    "totalPages": 71
  }
}
----
cf le chapitre <<appendix_search_results_v2>> pour une description de la structure de retour.

[[rest_full_text_search_results]]
===== {GET} /search/fullTextResults

Cette méthode permet d'obtenir les métadonnées des documents renvoyés par une requête *full-text* / *Plein-texte*. +
Cette recherche peut être complétée avec des critères de recherche *AIRS*.

Tout comme l'<<rest_search_results_v2,API>> décrite précédemment, les résultats sont [underline]#paginées#.

[CAUTION]
====
Dans la réponse, l'attribut *page.totalResults* (et donc *page.totalPages*) comptabilise [underline]#seulment# les résultats bruts de la recherche
*full-text*.

Ce résultat est potentiellement erroné/surévalué car :

* les droits documentaires ne sont calculés qu'au fil de l'eau (de la récupération des résultats)
* les critères additionnels (attribut *airsRequest*) ne sont appliqués également qu'à chaque récupération unitaire.

En cas d'appel de l'API sur une *page* (_attribut_) trop éloignée, les 2 attributs (*totalResults* et *totalPages*) seront ré-évaluées à leur valeur réelle.
====

[cols="1a,1a,4a,2a,3a",options="header"]
.Paramètres en entrée
|===
|Paramètre|Type|Description|Requis|Exemple
|*query*|{query}|Requête *full-text*|[red]*Oui*|_Digitech entreprise_
|*ctyCodes*|{query}|Liste des types de contenu dans lesquels la recherche est exécutée
[TIP]
====
Pour effectuer une recherche sur tous les types de contnues, vous pouvez spécifier \*.* . +
La recherche sera alors jouée sur tous les types de contenu ou ceux appartenant au *flowCode*
====
|[red]*Oui*|CR
|*flowCode*|{query}|Code du flux dans lequel la recherche est effectué|[green]*Non*|DEM_CONGE
|*airsRequest*|{query}|Requête AIRS|[green]*Non*|D_CREAT>01/01/2018
|*page*|{query}|Numéro de page souhaitée (voir la |[green]*Non*, défaut : *0*|
|*size*|{query}|nombre de résultats maximum renvoyés|[green]*Non*, défaut : *20*|
|*delegated*|{query}|*login* de l'utilisateur pour lequel la recherche sera réellement jouée (déléguée).
[CAUTION]
====
L'utilisateur *[underline]#authentifié#* doit posséder le droit *DOSSIERS_DELEGATE_SEARCH_APIS* pour pouvoir effectuer une recherche _"déléguée"_.
====
|[green]*Non*|_n.felix_
|===

[source]
.appel _curl_
----
curl -X 'GET' \
  'http[s]://<host>:<port>/<context>/rest/search/fullTextResults?query=digitech%20entreprise&ctyCodes=%2A.%2A&flowCode=CR&airsRequest=CR_DES%20%3D%20%22Sideral%20Ecologie%22&page=0' \
  -H 'accept: application/json' \
  -H 'Authorization: Basic <credencials>'
----

[cols="^1a,4a",options="header"]
.Réponses
|===
|Code Http|Description
^|[lime]*200*|Opération réussie (cf. <<search_getresultsjson_response_v2>>)
^|[red]*401*|Authentification non fournie
^|[red]*500*|Erreur interne au serveur/service
^|[red]*503*|Si le service *full-text* n'est pas disponible
|===

[[search_getfulltextresultsjson_response]]
[source,json]
.PageableFullTextSearchResults
----
{
  "documents": [
    {
      "id": 2724,
      "ctCode": "CR",
      "ctLabel": "Compte-Rendy",
      "fields": [
        {
          "code": "D_MODIF",
          "label": "Date de modification",
          "field": "28/09/2018 16:33:13"
        },
        {
          "code": "CR_THEME",
          "label": "Thème",
          "field": "173"
        },
        {
          "code": "D_CREAT",
          "label": "Date de création",
          "field": "28/09/2018 16:33:13"
        },
        {
          "code": "CR_DES",
          "label": "Désignation",
          "field": "Sideral Ecologie"
        },
        {
          "code": "CR_REDACTEUR",
          "label": "Rédacteur",
          "field": "7"
        },
        {
          "code": "CR_DATE",
          "label": "Date",
          "field": "28/09/2018 0:00:00"
        },
        {
          "code": "CR_RESUME",
          "label": "Résumé",
          "field": "CR de la 1e réunion du groupe"
        }
      ],
      "attachmentId": 2585,
      "score": 5.2279444,
      "fragment": "Quelques propositions Application directe N&eacute;cessitant &eacute;changes avec la direction (et avec les DP) Disposer pour <span class=\"highlight highlight1\">Digitech</span> d&rsquo;un container ext&eacute;rieur pour les papiers X - si non propos&eacute; par la ville, recourir &agrave; une association pour la r&eacute;cup&eacute;ration..."
    }
  ],
  "page": {
    "size": 1,
    "number": 0,
    "totalResults": 1,
    "totalPages": 1
  }
}
----
cf le chapitre <<appendix_fulltext_search_results>> pour une description de la structure de retour.