[[dossierContext_rest]]
=== DossierContext

==== Client

La classe `com.digitech.dossier.rest.ws.impl.DossierContextClient` de la librairie *com.digitech.airs:dossier-rest-client:{dossier-rest-client-version}* abstrait
l'utilisation
de cette *API*.

==== Méthodes
===== {GET} /dossierContext/flows

Cette méthode renvoie la liste des flux paramétrés au sein de l'application.

[source]
.appel _curl_
----
curl -X 'GET' \
  'http[s]://<host>:<port>/<context>/rest/dossierContext/flows' \
  -H 'accept: application/json' \
  -H 'Authorization: Basic <credencials>'
----

[cols="^1a,4a",options="header"]
.Réponses
|===
|Code Http|Description
|[lime]*200*|Opération réussie (cf. <<dossiercontext_getflowsjson_response>>)
|[red]*401*|Authentification non fournie
|[red]*500*|Erreur interne au serveur/service
|===

[[dossiercontext_getflowsjson_response]]
[source,json]
.Liste des flux
----
[
  {
    "code": "DOCUMENTATION",
    "label": "Flow created in simplified mode"
  },
  {
    "code": "REF",
    "label": "Flow created in simplified mode"
  },
  {
    "code": "CPA",
    "label": "Flow created in simplified mode"
  },
  {
    "code": "PRO",
    "label": "Flux Projet"
  },
  {
    "code": "CR",
    "label": "Flow created in simplified mode"
  }
]
----

cf le chapitre <<appendix_dossiercontext, en annexe>> pour une description de la structure de retour.

[[dossierContext_contentType_ctycode_old]]
===== {GET} /dossierContext/contentType/{ctyCode}

[CAUTION]
====
Ce {webservice} est déprécié. + Veuillez utiliser le service décrit <<dossierContext_contentType_ctycode_new, ici>>.
====

Cette méthode permet de récupérer la liste des informations d'un type de contenu.

[cols="1a,1a,4a,1a,2a",options="header"]
.Paramètres en entrée
|===
|Paramètre|Type|Description|Requis|Exemple
|*ctyCode*|{path}|Code du type de contenu|[red]*Oui*|DOC_CATEGORIE
|*flowCode*|{query}|Code du flux dans lequel le type de contenu est paramétré|[green]*Non*|DOCUMENTATION
|===

[source]
.appel _curl_
----
curl -X 'GET' \
  'http[s]://<host>:<port>/<context>/rest/dossierContext/contentType/DOC_CATEGORIE?flowCode=DOCUMENTATION' \
  -H 'accept: application/json' \
  -H 'Authorization: Basic <credencials>'
----

[cols="^1a,4a",options="header"]
.Réponses
|===
|Code Http|Description
^|[lime]*200*|Opération réussie (cf. <<dossiercontext_getcontenttypejson_response>>)
^|[red]*401*|Authentification non fournie
^|[red]*404*|Type de contenu non trouvé
^|[red]*500*|Erreur interne au serveur/service
|===

[[dossiercontext_getcontenttypejson_response]]
[source,json]
.WSContentTypeInfosType
----
{
  "WSContentTypeInfosType": {
    "code": "DOC_CATEGORIE",
    "id": 15,
    "description": "Catégorie",
    "readSecretLevels": [
      10
    ],
    "writeSecretLevels": [
      10
    ],
    "linksInfosList": [
      {
        "childContentType": {
          "code": "DOC_DOCUMENT",
          "id": 16,
          "description": "Document",
          "linksInfosList": []
        },
        "linkedFieldInfos": [
          {
            "fieldChildcode": "DOC_CAT_CODE",
            "fieldFathercode": "DOC_CAT_CODE"
          }
        ]
      }
    ]
  }
}
----

cf le chapitre <<appendix_dossiercontext_WSContentTypeInfosType, en annexe>> pour une description de la structure de retour.

===== {GET} /dossierContext/mandatoryFields/{ctyCode}

Cette méthode permet de récupérer la liste des champs obligatoires d'un type de contenu.

[cols="1a,1a,4a,1a,2a",options="header"]
.Paramètres en entrée
|===
|Paramètre|Type|Description|Requis|Exemple
|*ctyCode*|{path}|Code du type de contenu|[red]*Oui*|DOC_CATEGORIE
|*flowCode*|{query}|Code du flux dans lequel le type de contenu est paramétré|[green]*Non*|DOCUMENTATION
|===

[source]
.appel _curl_
----
curl -X 'GET' \
  'http[s]://<host>:<port>/<context>/rest/dossierContext/mandatoryFields/CR?flowCode=CR' \
  -H 'accept: application/json' \
  -H 'Authorization: Basic <credencials>'
----

[cols="^1a,4a",options="header"]
.Réponses
|===
|Code Http|Description
^|[lime]*200*|Opération réussie (cf. <<dossiercontext_getmandatoryfieldsjson_response>>)
^|[red]*401*|Authentification non fournie
^|[red]*404*|Type de contenu non trouvé
^|[red]*500*|Erreur interne au serveur/service
|===

[[dossiercontext_getmandatoryfieldsjson_response]]
[source,json]
.Structure de retour
----
[
  "CR_THEME",
  "CR_DES",
  "CR_REDACTEUR",
  "CR_DATE"
]
----

[[dossierContext_contentType_ctycode_new]]
===== {GET} /dossierContext/contentType/{ctCode}/{mode}

Cette méthode permet de récupérer la liste des informations d'un type de contenu.

[cols="1a,1a,4a,1a,2a",options="header"]
.Paramètres en entrée
|===
|Paramètre|Type|Description|Requis|Exemple
|*ctCode*|{path}|Code du type de contenu|[red]*Oui*|DOC_CATEGORIE
|*mode*|{path}|Définition des champs selon le mode suivant :

* *CONFIG*: ensemble des champs rattachés au content-type.
* *SEARCH*: champs disponibles en recherche de documents.
* *READ*: champs lors de la consultation d'un document.
* *INSERT*: champs lors de la création d'un document (*valeur par défaut*)
* *UPDATE*: champs lors de la mise à jour d'un document.
* *INDEX*: champs disponibles lors de l'indexation d'un document.
|[green]*Non*|INSERT
|*choices*|{query}|Obtention des valeurs autorisées pour les champs *référence*|[green]*Non*|
|===

[source]
.appel _curl_
----
curl -X 'GET' \
  'http[s]://<host>:<port>/<context>/rest/dossierContext/contentType/CR/UPDATE' \
  -H 'accept: application/json' \
  -H 'Authorization: Basic <credencials>'
----

[cols="^1a,4a",options="header"]
.Réponses
|===
|Code Http|Description
^|[lime]*200*|Opération réussie (cf. exemple <<dossiercontext_getcontenttypejson_new_response1, ici>> ou <<dossiercontext_getcontenttypejson_new_response2,
là>> ou <<dossiercontext_getcontenttypejson_new_response3,encore là>>)
^|[red]*401*|Authentification non fournie
^|[red]*403*|Type de contenu non autorisé pour l'utilisateur
^|[red]*404*|Type de contenu non trouvé
^|[red]*500*|Erreur interne au serveur/service
|===

[[dossiercontext_getcontenttypejson_new_response1]]
[source,json]
.WSContentTypeInfo, *mode==INSERT*
----
{
  "contentType": {
    "code": "CR",
    "label": "Compte rendu",
    "mode": "INSERT",
    "readSecretLevels": [
      10
    ],
    "writeSecretLevels": [
      10
    ],
    "children": [],
    "fields": [
      {
        "id": 123,
        "code": "CR_DES",
        "label": "Désignation",
        "type": "text",
        "required": true,
        "reference": false,
        "multivalued": false,
        "system": false,
        "readonly": false
      },
      {
        "id": 124,
        "code": "CR_DATE",
        "label": "Date événement",
        "type": "date",
        "required": true,
        "reference": false,
        "multivalued": false,
        "system": false,
        "readonly": false
      },
      {
        "id": 125,
        "code": "CR_RESUME",
        "label": "Résumé",
        "type": "text",
        "required": false,
        "reference": false,
        "multivalued": false,
        "system": false,
        "readonly": false
      },
      {
        "id": 126,
        "code": "CR_THEME",
        "label": "Thématique",
        "type": "authority",
        "required": true,
        "reference": true,
        "multivalued": false,
        "system": false,
        "readonly": false
      },
      {
        "id": 127,
        "code": "CR_REDACTEUR",
        "label": "Rédacteur",
        "type": "user",
        "required": true,
        "reference": true,
        "multivalued": false,
        "system": false,
        "readonly": false
      }
    ]
  }
}
----

cf le chapitre <<appendix_dossiercontext_WSContentTypeInfo, en annexe>> pour une description de la structure de retour.

[[dossierContext_contentType_links]]
===== {GET} /dossierContext/contentType/links/{ctCode}

Cette méthode permet de récupérer les informations sur les liens entre content-types.

[cols="1a,1a,4a,1a,2a",options="header"]
.Paramètres en entrée
|===
|Paramètre|Type|Description|Requis|Exemple
|*ctCode*|{path}|Code du type de contenu|[red]*Oui*|DOC_CATEGORIE
|*flowCode*|{query}|Code du flux dans lequel le type de contenu est paramétré

[CAUTION]
====
Quel que soit le content-type que vous précisez, la hiérarchie complète sera retournée par l'API, c'est-à-dire en remontant au content-type *racine*.
====
|[green]*Non*|DOCUMENTATION
|===

[source]
.appel _curl_
----
curl -X 'GET' \
  'http[s]://<host>:<port>/<context>/rest/dossierContext/contentType/links/DOC_DOCUMENT' \
  -H 'accept: application/json' \
  -H 'Authorization: Basic <credencials>'
----

[cols="^1a,4a",options="header"]
.Réponses
|===
|Code Http|Description
^|[lime]*200*|Opération réussie (cf. <<dossiercontext_getcontenttype_links_json_response>>)
^|[red]*401*|Authentification non fournie
^|[red]*404*|Type de contenu non trouvé
^|[red]*500*|Erreur interne au serveur/service
|===

[[dossiercontext_getcontenttype_links_json_response]]
[source,json]
.WSContentTypeLinkInfo
----
{
  "contentTypeLink": {
    "code": "DOC_CATEGORIE",
    "label": "Catégorie",
    "children": [
      {
        "code": "DOC_DOCUMENT",
        "label": "Document",
        "linkedFields": [
          {
            "code": "DOC_CAT_CODE",
            "parentFieldCode": "DOC_CAT_CODE"
          }
        ]
      }
    ]
  }
}
----

cf le chapitre <<appendix_dossiercontext_WSContentTypeLinkInfo, en annexe>> pour une description de la structure de retour.

===== {GET} /dossierContext/contentTypes

Cette méthode permet de récupérer la liste des content-types, pour chaque *flow*

[cols="1a,1a,4a,1a,2a",options="header"]
.Paramètres en entrée
|===
|Paramètre|Type|Description|Requis|Exemple
|*hierarchy*|{query}|Est-ce que la hiérarchie entre content-types doit être calculée|[green]*Non*|
|===

[source]
.appel _curl_
----
curl -X 'GET' \
  'http[s]://<host>:<port>/<context>/rest/dossierContext/contentTypes?hierarchy=false' \
  -H 'accept: application/json' \
  -H 'Authorization: Basic <credencials>'
----

[cols="^1a,4a",options="header"]
.Réponses
|===
|Code Http|Description
^|[lime]*200*|Opération réussie (cf. <<dossiercontext_contentTypes_json_response>>)
^|[red]*401*|Authentification non fournie
^|[red]*404*|Type de contenu non trouvé
^|[red]*500*|Erreur interne au serveur/service
|===


[[dossiercontext_contentTypes_json_response]]
[source,json]
----
{
  "MONTEE_SUR_CALE": [
    {
      "code": "ARMATEUR",
      "label": "Armateur",
      "children": [
        {
          "code": "NAVIRE",
          "label": "Navire",
          "children": [
            {
              "code": "MONTEE_SUR_CALE",
              "label": "Montée sur cale",
              "children": [
                {
                  "code": "DOC_MONTEE",
                  "label": "Documents"
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "code": "ARMATEUR",
      "label": "Armateur",
      "children": [
        {
          "code": "NAVIRE",
          "label": "Navire",
          "children": [
            {
              "code": "MONTEE_SUR_CALE",
              "label": "Montée sur cale",
              "children": [
                {
                  "code": "DOC_MONTEE",
                  "label": "Documents"
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "code": "ARMATEUR",
      "label": "Armateur",
      "children": [
        {
          "code": "NAVIRE",
          "label": "Navire",
          "children": [
            {
              "code": "MONTEE_SUR_CALE",
              "label": "Montée sur cale",
              "children": [
                {
                  "code": "DOC_MONTEE",
                  "label": "Documents"
                }
              ]
            }
          ]
        }
      ]
    },
    {
      "code": "ARMATEUR",
      "label": "Armateur",
      "children": [
        {
          "code": "NAVIRE",
          "label": "Navire",
          "children": [
            {
              "code": "MONTEE_SUR_CALE",
              "label": "Montée sur cale",
              "children": [
                {
                  "code": "DOC_MONTEE",
                  "label": "Documents"
                }
              ]
            }
          ]
        }
      ]
    }
  ],
  "COURRIER": [
    {
      "code": "DCOU_COURRIER",
      "label": "Courriers"
    }
  ],
  "REF_DOCUMENT": [
    {
      "code": "DOC_TECH",
      "label": "Documentations techniques"
    }
  ]
}
----

===== {GET} /dossierContext/contentTypes/{flowCode}

Cette méthode permet de récupérer la liste des content-types, pour un *flow/flux* précisé.

[cols="1a,1a,4a,1a,2a",options="header"]
.Paramètres en entrée
|===
|Paramètre|Type|Description|Requis|Exemple
|*flowCode*|{path}|Code du flux|[red]*Oui*|*TADA*
|*hierarchy*|{query}|Est-ce que la hiérarchie entre content-types doit être calculée|[green]*Non*|
|===

[source]
.appel _curl_
----
curl -X 'GET' \
  'http[s]://<host>:<port>/<context>/rest/dossierContext/contentTypes/MONTEE_SUR_CALE?hierarchy=true' \
  -H 'accept: application/json' \
  -H 'Authorization: Basic <credencials>'
----

[cols="^1a,4a",options="header"]
.Réponses
|===
|Code Http|Description
^|[lime]*200*|Opération réussie (cf. <<dossiercontext_contentTypes_flowcode_json_response>>)
^|[red]*401*|Authentification non fournie
^|[red]*404*|Flux non trouvé
^|[red]*500*|Erreur interne au serveur/service
|===


[[dossiercontext_contentTypes_flowcode_json_response]]
[source,json]
----
[
  {
    "code": "ARMATEUR",
    "label": "Armateur",
    "children": [
      {
        "code": "NAVIRE",
        "label": "Navire",
        "children": [
          {
            "code": "MONTEE_SUR_CALE",
            "label": "Montée sur cale",
            "children": [
              {
                "code": "DOC_MONTEE",
                "label": "Documents"
              }
            ]
          }
        ]
      }
    ]
  },
  {
    "code": "ARMATEUR",
    "label": "Armateur",
    "children": [
      {
        "code": "NAVIRE",
        "label": "Navire",
        "children": [
          {
            "code": "MONTEE_SUR_CALE",
            "label": "Montée sur cale",
            "children": [
              {
                "code": "DOC_MONTEE",
                "label": "Documents"
              }
            ]
          }
        ]
      }
    ]
  },
  {
    "code": "ARMATEUR",
    "label": "Armateur",
    "children": [
      {
        "code": "NAVIRE",
        "label": "Navire",
        "children": [
          {
            "code": "MONTEE_SUR_CALE",
            "label": "Montée sur cale",
            "children": [
              {
                "code": "DOC_MONTEE",
                "label": "Documents"
              }
            ]
          }
        ]
      }
    ]
  },
  {
    "code": "ARMATEUR",
    "label": "Armateur",
    "children": [
      {
        "code": "NAVIRE",
        "label": "Navire",
        "children": [
          {
            "code": "MONTEE_SUR_CALE",
            "label": "Montée sur cale",
            "children": [
              {
                "code": "DOC_MONTEE",
                "label": "Documents"
              }
            ]
          }
        ]
      }
    ]
  }
]
----