[[extended_search_rest]]
=== ExtendSearch

[NOTE]
====
Ce { webservice} n'est disponible qu'à partir de la version *7.1* de {arcadeged}
====

==== Client

La classe `com.digitech.dossier.rest.ws.IExtendedSearchClient` de la librairie *com.digitech.airs:dossier-rest-client:{dossier-rest-client-version}* abstrait l'utilisation
de cette *API*.

==== Authentification

Ce {webservice} requiert une https://tools.ietf.org/html/rfc7617[*authentification basique*^].

==== Méthodes

[[extended_search_rest_v1]]
===== {GET} /search4FieldsAndAttachments

Cette méthode permet à partir d'une requête {airs} de récupérer

* des documents
* leurs _metadata_ (champs)
* et les informations sur les pièces jointes de chaque document

[cols="1a,1a,4a,1a,2a",options="header"]
.Paramètres en entrée
|===
|Paramètre|Type|Description|Requis|Exemple
|*airsRequest*|{query}|Requête {airs}|[red]*Oui*|D_CREAT >= "28/03/2020"
|*ctyCodes*|{query}|Liste des types de contenu dans lesquels la recherche est exécutée.
[TIP]
====
Pour effectuer une recherche sur tous les types de contnues, vous pouvez spécifier \*.* . +
La recherche sera alors jouée sur tous les types de contenu ou ceux appartenant au *flowCode*
====
|[red]*Oui*|CR
|*flowCode*|{query}|Code du flux dans lequel la recherche est effectuée. +
Si Vide, celui-ci sera déduit de la liste des types de contenu|[red]*Oui*|CR
|*continuationToken*|{query}|Clé de _continuation_. +
Le nombre de résultats reçus est limité à *20* (par défaut, côté {arcadeged}. +
Si vous souhaitez plus de résultats, le {webservice} doit être rappelé en ajoutant cette clé.|[green]*Non*
|OTU4ODQ0ZTFhMDllODViYTNjN2JiNThkOWM5YjQwNDAjIzE1OTI5MTc3MTM2MDYjIzQ1ODYjIzIw
|===

[source]
.appel _curl_
----
curl -X 'GET' \
  'http://<host>:<port>/<context>/rest/extendSearch/search4FieldsAndAttachments?airsRequest=D_CREAT%20%3E%3D%20%2201%2F01%2F2020%22&ctyCodes=CR' \
  -H 'accept: application/json' \
  -H 'Authorization: Basic <credencials>'

curl -X 'GET' \
  'http://<host>:<port>/<context>/rest/extendSearch/search4FieldsAndAttachments?airsRequest=D_CREAT%20%3E%3D%20%2201%2F01%2F2020%22&ctyCodes=CR&ctyCodes=PRO_CLIENT' \
  -H 'accept: application/json' \
  -H 'Authorization: Basic <credencials>'
----

[source]
.appel _requête_
----
http://<host>:<port>/<context>/rest/extendSearch/search4FieldsAndAttachments?airsRequest=D_CREAT%20%3E%3D%20%2201%2F01%2F2020%22&ctyCodes=CR

http://<host>:<port>/<context>/rest/extendSearch/search4FieldsAndAttachments?airsRequest=D_CREAT%20%3E%3D%20%2201%2F01%2F2020%22&ctyCodes=CR&ctyCodes=PRO_CLIENT
----

[NOTE]
====
La valeur _D_CREAT%20%3E%3D%20%2201%2F01%2F2020%22_ correspond à *D_CREAT >= "01/01/2020"*
====

[cols="^1a,4a",options="header"]
.Réponses
|===
|Code Http|Description
|[lime]*200*|Opération réussie (cf. <<extendedearchjson_response>>)
|[red]*401*|Authentification non fournie
|[red]*500*|Erreur interne au serveur/service
|===

[[extendedearchjson_response]]
[source,json]
.Structure de retour
----
{
  "WSExtendSearchResult": {
      "resultNumber": 0,
      "continuationToken": "string",
      "documents": [
        {
          "refAirs": 0,
          "secretLevel": 0,
          "contentType": "string",
          "fields": [
            {
              "code": "string",
              "label": "string",
              "value": "string",
              "refValue": "string"
            }
          ],
          "attachments": [
            {
              "id": 0,
              "label": "string",
              "fileName": "string",
              "airsType": "string",
              "versions": [
                {
                  "id": 0,
                  "label": "string",
                  "fileName": "string",
                  "version": 0,
                  "date": "string"
                }
              ]
            }
          ]
        }
      ]
    }
}
----

cf. le chapitre <<appendix_extendsearch_wsextendsearchresult>> pour une description de la structure de retour.

[[extended_search_rest_v2]]
===== {GET} /v2/search4FieldsAndAttachments

Cette méthode est identique à la <<extended_search_rest_v1, précédente>>, mais permet en plus de déléguer la recherche effectuée sur un compte différent de
celui authentifié à l'API.

[NOTE]
====
La raison pour laquelle la méthode précédente n'est pas simplement utilisée est de conserver une *rétro-compatibilité* avec les clients existants et ainsi
minimiser les opérations de migration.
====


[cols="1a,1a,4a,2a,3a",options="header"]
.Paramètres en entrée
|===
|Paramètre|Type|Description|Requis|Exemple
5+|voir paramètres définis au chapitre <<extended_search_rest_v1,précédent>>
|*sort*|{query}|Critères de tri, défini par le *<code du champ>[,<direction>]*
[TIP]
====
Si vous souhaitez cumuler les champs de tri, veuillez simplement répéter l'attribut, ex.
[source,text]
----
sort=D_CREAT,desc&sort=RESUME,asc&sort=TITRE
----
====
|[green]*Non*|*D_CREAT,desc*
|*delegated*|{query}|login de l'utilisateur avec lequel la requête sera jouée|[red]*Oui*|*n.felix*
|===

[[extended_search_rest_v3]]
===== {GET} /results

Cette méthode est similaire à la <<extended_search_rest_v2, précédente>> en permettant en sus de naviguer (_bidirectionnellement_) parmi la plage de résultats
(en lieu et place de l'utilisation du _continuationToken_)

[cols="1a,1a,4a,2a,3a",options="header"]
.Paramètres en entrée
|===
|Paramètre|Type|Description|Requis|Exemple
5+|voir paramètres définis au chapitre <<extended_search_rest_v2,précédent>>
|*page*|{query}|Numéro de page souhaitée (voir la |[green]*Non*, défaut : *0*|
|*size*|{query}|nombre de résultats maximum renvoyés|[green]*Non*, défaut : *20*|
|===

[source]
.appel _curl_
----
curl -X 'GET' \
  'http://pc-nfe2.digitech.lan:7381/dossier81/rest/extendSearch/results?airsRequest=D_CREAT%3C24%2F12%2F2024&ctyCodes=CR&page=1&size=25' \
  -H 'accept: application/json' \
  -H 'Authorization: Basic <credencials>'
----

[source]
.appel _requête_
----
http://<host>:<port>/<context>/rest/extendSearch/results?airsRequest=D_CREAT%3C24%2F12%2F2024&ctyCodes=CR&page=1&size=25
----

[[extendedearchjson_response_results]]
[source,json]
.Structure de retour
----
{
  "results": {
    "documents": [
      {
        "refAirs": 2103,
        "secretLevel": 10,
        "contentType": "CR",
        "fields": [
          {
            "code": "D_MODIF",
            "label": "Date de modification",
            "value": "08/02/2021 14:48:10"
          },
          {
            "code": "CR_THEME",
            "label": "Thématique",
            "value": "Réunion Transverse",
            "refValue": "172"
          },
          {
            "code": "D_CREAT",
            "label": "Date de création",
            "value": "01/01/2001 0:00:00"
          },
          {
            "code": "CR_DES",
            "label": "Désignation",
            "value": "CR réunion transverse-1"
          },
          {
            "code": "CR_REDACTEUR",
            "label": "Rédacteur",
            "value": "Poli Marie-pierre",
            "refValue": "32"
          },
          {
            "code": "CR_DATE",
            "label": "Date événement",
            "value": "01/06/2022 0:00:00"
          },
          {
            "code": "CR_RESUME",
            "label": "Résumé",
            "value": ""
          },
          {
            "code": "T_PRIOR",
            "label": "Priorité",
            "value": ""
          },
          {
            "code": "MULTI",
            "label": "test champs multi",
            "value": ""
          },
          {
            "code": "CORRES",
            "label": "correspondent",
            "value": ""
          },
          {
            "code": "MASQUE_NUM",
            "label": "test masque",
            "value": ""
          }
        ],
        "attachments": []
      },
      {
        "refAirs": 2230,
        "secretLevel": 10,
        "contentType": "CR",
        "fields": [
          {
            "code": "D_MODIF",
            "label": "Date de modification",
            "value": "11/02/2021 15:43:49"
          },
          {
            "code": "CR_THEME",
            "label": "Thématique",
            "value": "Réunion Transverse",
            "refValue": "172"
          },
          {
            "code": "D_CREAT",
            "label": "Date de création",
            "value": "01/01/2001 0:00:00"
          },
          {
            "code": "CR_DES",
            "label": "Désignation",
            "value": "CR de la réunion transverse du lundi 28 mai 18-1"
          },
          {
            "code": "CR_REDACTEUR",
            "label": "Rédacteur",
            "value": "Aramburu Eric",
            "refValue": "8"
          },
          {
            "code": "CR_DATE",
            "label": "Date événement",
            "value": "01/06/2022 0:00:00"
          },
          {
            "code": "CR_RESUME",
            "label": "Résumé",
            "value": ""
          },
          {
            "code": "T_PRIOR",
            "label": "Priorité",
            "value": ""
          },
          {
            "code": "MULTI",
            "label": "test champs multi",
            "value": ""
          },
          {
            "code": "CORRES",
            "label": "correspondent",
            "value": ""
          },
          {
            "code": "MASQUE_NUM",
            "label": "test masque",
            "value": ""
          }
        ],
        "attachments": [
          {
            "id": 2199,
            "label": "00_Compte-rendu_reunion_transverse_du_28_mai__20180528170353993.pdf",
            "fileName": "00_Compte-rendu_reunion_transverse_du_28_mai__20180528170353993.pdf",
            "airsType": "ORIGINAL"
          }
        ]
      },
      ...
    ],
    "page": {
      "size": 25,
      "number": 1,
      "totalResults": 2441,
      "totalPages": 98
    }
  }
}
----

cf. le chapitre <<appendix_extendsearch_pageableextendsearchresults>> pour une description de la structure de retour.