[[admin_user_rest]]
==== Utilisateurs

[NOTE]
====
Ce {webservice} n'est disponible qu'à partir de la version {9_0} de {arcadeged}
====

===== Client

La classe `com.digitech.dossier.rest.ws.admin.impl.UserClient` de la librairie *com.digitech.airs:dossier-rest-client:{dossier-rest-client-version}* abstrait
l'utilisation de cette *API* ({java} seulement)

[IMPORTANT]
====
L'utilisateur connecté doit posséder le droit *DOSSIER_ADM_AIRS_ADMIN*.
====

===== Méthodes

====== {GET} /admin/users

Cette méthode permet de récupérer la liste de tous les utilisateurs et certaines de leurs propriétés.

[cols="1a,1a,4a,1a,2a",options="header"]
.Paramètres en entrée
|===
|Paramètre|Type|Description|Requis|Exemple
|*enabledOnly*|{query}|Récupérer seulement les utilisateurs actifs (défaut : *true*)|[red]*Non*|
|*profiles*|{query}|Récupérer également les profils de chaque utilisateur (défaut : *false*)|[red]*Non*|
|*rights*|{query}|Récupérer également les droits de chaque utilisateur (défaut : *false*)|[red]*Non*|
|===

[source]
.appel _curl_
----
curl -X 'GET' \
  'http[s]://<host>:<port>/<context>/rest/admin/users?enabledOnly=true&profiles=false&rights=false \
  -H 'accept: application/json' \
  -H 'Authorization: Basic <credencials>'
----

[cols="^1a,4a",options="header"]
.Réponses
|===
|Code Http|Description
|[lime]*200*|Opération réussie (cf. <<admin_user_list_rest_response1>>)
|[red]*401*|Authentification non fournie
|[red]*403*|Utilisateur non autorisé à effectuer cette action
|[red]*500*|Erreur interne au serveur/service
|===

[[admin_user_list_rest_response1]]
[source,json]
.Retour, liste des utilisateurs
----
[
  {
    "id": 1,
    "login": "n.felix",
    "lastname": "FÉLIX",
    "firstname": "nicolas",
    "email": nicolas.felix@digitech.fr,
    "enabled": true,
    "profiles": [
      {
        "id": 363,
        "code": "ADMIN_DOSSIER",
        "label": "Administrateur de Dossier"
      },
      {
        "id": 366,
        "code": "ACCES_GED",
        "label": "Accès à la GED"
      }
    ],
    "rights": [
      {
        "id": 19,
        "code": "CONSULTATION",
        "label": "Consultation des données"
      },
      {
        "id": 27,
        "code": "SECURITY_USER",
        "label": "Accès et Sécurité : Gestion des utilisateurs"
      }
    ]
  }
]
----

====== {GET} /admin/user/{userLogin}

Cette méthode permet de récupérer la liste d'utilisateurs à partir de leur *login* et certaines de leurs propriétés.

[cols="1a,1a,4a,1a,2a",options="header"]
.Paramètres en entrée
|===
|Paramètre|Type|Description|Requis|Exemple
|*userLogin*|{path}|login de l'utilisateur souhaité|[red]*Oui*|
|*profiles*|{query}|Récupérer également les profils de chaque utilisateur (défaut : *false*)|[red]*Non*|
|*rights*|{query}|Récupérer également les droits de chaque utilisateur (défaut : *false*)|[red]*Non*|
|===

[source]
.appel _curl_
----
curl -X 'GET' \
  'http[s]://<host>:<port>/<context>/rest/admin/user/n.felix?profiles=false&rights=false \
  -H 'accept: application/json' \
  -H 'Authorization: Basic <credencials>'
----

[cols="^1a,4a",options="header"]
.Réponses
|===
|Code Http|Description
|[lime]*200*|Opération réussie (cf. <<admin_user_login_list_rest_response1>>)
|[red]*401*|Authentification non fournie
|[red]*403*|Utilisateur non autorisé à effectuer cette action
|[red]*404*|Utilisateur non trouvé
|[red]*500*|Erreur interne au serveur/service
|===

[[admin_user_login_list_rest_response1]]
[source,json]
.Retour, liste des utilisateurs
----
[
  {
    "id": 1,
    "login": "n.felix",
    "lastname": "FÉLIX",
    "firstname": "nicolas",
    "email": "nicolas.felix@digitech.fr",
    "enabled": true,
    "profiles": [
      {
        "id": 363,
        "code": "ADMIN_DOSSIER",
        "label": "Administrateur de Dossier"
      },
      {
        "id": 366,
        "code": "ACCES_GED",
        "label": "Accès à la GED"
      }
    ],
    "rights": [
      {
        "id": 19,
        "code": "CONSULTATION",
        "label": "Consultation des données"
      },
      {
        "id": 27,
        "code": "SECURITY_USER",
        "label": "Accès et Sécurité : Gestion des utilisateurs"
      }
    ]
  }
]
----

====== {GET} /admin/user/{userId}

[NOTE]
====
Identique au web service précédent, automatiquement routé vers celui-ci si la paramètre *userId* est un *numérique*.
====

====== {PUT} /admin/user/{userLogin}/profile/{profile}

Cette méthode permet d'ajouter un *profil* à un utilisateur.

[cols="1a,1a,4a,1a,2a",options="header"]
.Paramètres en entrée
|===
|Paramètre|Type|Description|Requis|Exemple
|*userLogin*|{path}|login de l'utilisateur souhaité|[red]*Oui*|
|*profile*|{path}|Code du profil à ajouter|[red]*true*|
|===

[source]
.appel _curl_
----
curl -X 'PUT' \
  'http[s]://<host>:<port>/<context>/rest/admin/user/n.felix?profiles=false&rights=false \
  -H 'accept: application/json' \
  -H 'Authorization: Basic <credencials>'
----

[cols="^1a,4a",options="header"]
.Réponses
|===
|Code Http|Description
|[lime]*204*|Opération réussie (aucune structure de retour)
|[red]*304*|Aucun changement appliqué
|[red]*401*|Authentification non fournie
|[red]*403*|Utilisateur non autorisé à effectuer cette action
|[red]*404*|Utilisateur ou profil non trouvé
|[red]*500*|Erreur interne au serveur/service
|===

====== {PUT} /admin/user/{userId}/profile/{profile}

[NOTE]
====
Identique au web service précédent, automatiquement routé vers celui-ci si la paramètre *userId* est un *numérique*.
====

====== {DELETE} /admin/user/{userLogin}/profile/{profile}

Cette méthode permet de supprimer un *profil* d'un utilisateur.

[cols="1a,1a,4a,1a,2a",options="header"]
.Paramètres en entrée
|===
|Paramètre|Type|Description|Requis|Exemple
|*userLogin*|{path}|login de l'utilisateur souhaité|[red]*Oui*|
|*profile*|{path}|Code du profil à supprimer|[red]*true*|
|===

[source]
.appel _curl_
----
curl -X 'DELETE' \
  'http[s]://<host>:<port>/<context>/rest/admin/user/n.felix?profiles=false&rights=false \
  -H 'accept: application/json' \
  -H 'Authorization: Basic <credencials>'
----

[cols="^1a,4a",options="header"]
.Réponses
|===
|Code Http|Description
|[lime]*204*|Opération réussie (aucune structure de retour)
|[red]*304*|Aucun changement appliqué
|[red]*401*|Authentification non fournie
|[red]*403*|Utilisateur non autorisé à effectuer cette action
|[red]*404*|Utilisateur ou profil non trouvé
|[red]*500*|Erreur interne au serveur/service
|===

====== {DELETE} /admin/user/{userId}/profile/{profile}

[NOTE]
====
Identique au web service précédent, automatiquement routé vers celui-ci si la paramètre *userId* est un *numérique*.
====